// Public chapter metadata for Kanzul Mikban (Prompt 27 — protected-content
// migration). Generated once from the manuscript's own chapter id/number/
// title — no paragraph text, no method quotes, no source material beyond
// plain chapter labels. Safe for any client-reachable code (navigation,
// search, source-label lookups, offline URL enumeration): none of it is the
// protected book content itself. The full chapter text (paragraphs) now
// lives only in lib/server/content/kanzulMikban.ts, a server-only module.

export interface KmChapterMeta {
  id: string;
  number: number | null;
  title: string;
}

export const KM_CHAPTER_META: KmChapterMeta[] = [
  { id: "traveling-business-and-if-you-will-return-from", number: 1, title: "Traveling, Business, and If You Will Return from the Trip or Not" },
  { id: "if-you-want-to-know-if-you-will", number: 2, title: "If You Want to Know If You Will Get Money Today or Not" },
  { id: "business-profit-and-loss", number: 3, title: "Business, Profit, and Loss" },
  { id: "hunting-in-water-and-on-land-and-searching", number: 4, title: "Hunting in Water and on Land, and Searching for Anything" },
  { id: "if-you-will-win-a-fight-war-or", number: 5, title: "If You Will Win a Fight, War, or Court Case" },
  { id: "if-you-want-to-know-where-your-enemy", number: 6, title: "If You Want to Know Where Your Enemy or a Thief Is Hidden" },
  { id: "marriage-and-its-blessings", number: 7, title: "Marriage and Its Blessings" },
  { id: "if-she-s-going-to-stay-in-the", number: null, title: "Sub-topic: If She's Going to Stay in the Marriage or Not" },
  { id: "if-one-will-stay-in-a-particular-place", number: 8, title: "If One Will Stay in a Particular Place or Not, and If It's Good or Not" },
  { id: "sickness-if-he-she-will-survive", number: 9, title: "Sickness (If He/She Will Survive)" },
  { id: "if-your-lost-thing-is-still-around-or", number: 10, title: "If Your Lost Thing Is Still Around or Is Gone" },
  { id: "if-you-want-to-know-if-you-will-2", number: 11, title: "If You Want to Know If You Will Be Successful in Life, at Home, or Have to Travel Away from Home" },
  { id: "if-you-want-to-know-if-you-will-3", number: 12, title: "If You Want to Know If You Will Be Rich in Life or Not" },
  { id: "if-you-will-get-children-from-a-lady", number: 13, title: "If You Will Get Children from a Lady You Want to Marry" },
  { id: "if-a-pregnancy-is-going-to-be-stable", number: 14, title: "If a Pregnancy Is Going to Be Stable or Not (Good Condition)" },
  { id: "if-things-will-be-better-for-the-questioner", number: 15, title: "If Things Will Be Better for the Questioner or Not" },
  { id: "if-you-will-overcome-your-enemy-or-not", number: 16, title: "If You Will Overcome Your Enemy or Not" },
  { id: "if-something-will-happen-in-an-hour-day", number: 17, title: "If Something Will Happen in an Hour, Day, Week, Month, or Year" },
  { id: "if-you-will-get-your-stolen-things-back", number: 18, title: "If You Will Get Your Stolen Things Back" },
  { id: "if-you-will-win-a-case-in-court", number: 19, title: "If You Will Win a Case in Court, Chief Palace, a Fight, or War" },
  { id: "who-will-win-an-election-or-a-chieftaincy", number: 20, title: "Who Will Win an Election or a Chieftaincy Title" },
  { id: "if-your-wife-or-sister-has-had-sex", number: 21, title: "If Your Wife or Sister Has Had Sex or Not" },
  { id: "if-it-s-good-to-stay-in-a", number: null, title: "If It's Good to Stay in a Particular House" },
  { id: "if-it-s-good-to-stay-in-a-2", number: 22, title: "If It's Good to Stay in a Town or Not" },
  { id: "is-there-much-trees-water-sand-or-stones", number: 23, title: "Is There Much Trees, Water, Sand, or Stones in the Area You Are Going To" },
  { id: "if-you-will-be-safe-entering-a-canoe", number: 24, title: "If You Will Be Safe Entering a Canoe, or Will Get Fish from Fishing" },
  { id: "if-there-are-armed-robbers-on-your-way", number: 25, title: "If There Are Armed Robbers on Your Way" },
  { id: "if-there-will-be-a-fight-argument-etc", number: 26, title: "If There Will Be a Fight, Argument, etc" },
  { id: "about-farming-and-food-in-the-year", number: 27, title: "About Farming and Food in the Year" },
  { id: "if-you-will-get-money-or-good-strangers", number: 28, title: "If You Will Get Money or Good Strangers That Same Day or Not" },
  { id: "if-you-will-be-successful-where-you-are", number: 29, title: "If You Will Be Successful Where You Are Going" },
  { id: "continued-from-chapter-twenty-eight", number: null, title: "Reading the Gift/Visitor Figures (continued from Chapter Twenty-Eight)" },
  { id: "reading-the-gift-visitor-figures-end-of-chapter", number: null, title: "Continued from Part 1 — Reading the Gift/Visitor Figures (end of Chapter Twenty-Eight/Twenty-Nine material)" },
  { id: "if-you-will-be-successful-and-get-what", number: 30, title: "If You Will Be Successful and Get What You Want from the Trip/Traveling" },
  { id: "about-a-lost-thing-stolen-things", number: 31, title: "About a Lost Thing / Stolen Things" },
  { id: "if-it-will-rain-today-or-not", number: 32, title: "If It Will Rain Today or Not" },
  { id: "if-someone-loves-you-much-less-or-not", number: 33, title: "If Someone Loves You Much, Less, or Not at All" },
  { id: "if-your-enemies-are-working-against-you-or", number: 34, title: "If Your Enemies Are Working Against You or Not" },
  { id: "if-your-family-is-doing-well-while-you", number: 35, title: "If Your Family Is Doing Well (While You Are Far from Them)" },
  { id: "if-you-want-to-locate-someone-or-something", number: 36, title: "If You Want to Locate Someone or Something" },
  { id: "how-to-predict-a-game-who-will-win", number: 37, title: "How to Predict a Game, Who Will Win or Lose" },
  { id: "if-two-lovers-will-be-compatible-for-marriage", number: 38, title: "If Two Lovers Will Be Compatible for Marriage (Their Star Signs)" },
  { id: "if-your-visitor-or-the-person-that-comes", number: 39, title: "If Your Visitor, or the Person That Comes to You, Is a Good or Bad Person" },
  { id: "if-spiritual-work-you-want-to-do-for", number: 40, title: "If Spiritual Work You Want to Do for Someone Will Work or Not" },
  { id: "the-person-that-took-an-item-stole-something", number: 41, title: "The Person That Took an Item / Stole Something" },
  { id: "if-you-will-get-what-you-want-from", number: 42, title: "If You Will Get What You Want from Where You Are Going" },
  { id: "the-real-behavior-character-or-life-of-someone", number: 43, title: "The Real Behavior/Character or Life of Someone You Want to Get Married to (in Future)" },
  { id: "if-a-lady-or-man-will-accept-your", number: 44, title: "If a Lady or Man Will Accept Your Love Proposal or Not" },
  { id: "if-you-will-get-the-lost-thing-back", number: 45, title: "If You Will Get the Lost Thing Back" },
  { id: "how-to-make-one-win-over-the-other", number: 46, title: "How to Make One Win Over the Other Opponents (Enemies)" },
  { id: "if-a-lady-is-pregnant-or-not", number: 47, title: "If a Lady Is Pregnant or Not" },
  { id: "if-it-s-a-male-or-female-child", number: 48, title: "If It's a Male or Female Child" },
  { id: "if-something-is-closer-to-you-or-far", number: 49, title: "If Something Is Closer to You or Far Away from You" },
  { id: "if-you-will-get-gold-in-a-place", number: 50, title: "If You Will Get Gold in a Place Where You Are Working" },
  { id: "if-things-are-going-to-be-well-this", number: 51, title: "If Things Are Going to Be Well This Year or Not (Yearly News)" },
  { id: "the-friendship-between-two-people-if-it-s", number: 52, title: "The Friendship Between Two People, If It's Good or Not" },
  { id: "the-consequence-of-friendship-between-two-people", number: null, title: "The Consequence of Friendship Between Two People" },
  { id: "if-a-querent-is-asking-about-someone-or", number: 53, title: "If a Querent Is Asking About Someone or About Him/Herself" },
  { id: "where-your-success-is-or-where-you-will", number: 54, title: "Where Your Success Is, or Where You Will Make It in Life" },
  { id: "the-whereabouts-of-a-thief-or-robbers", number: 55, title: "The Whereabouts of a Thief or Robbers" },
  { id: "about-a-pregnancy-if-it-s-a-boy", number: 56, title: "About a Pregnancy, If It's a Boy or a Girl" },
  { id: "s-if-you-want-to-know-if-she", number: null, title: "Additional Methods — If You Want to Know If She's Pregnant" },
  { id: "when-to-travel-daytime-or-night-time", number: 57, title: "When to Travel, Daytime or Night Time" },
  { id: "if-couples-have-had-sex-or-not", number: 58, title: "If Couples Have Had Sex or Not" },
  { id: "the-secret-of-the-querent-in-a-chart", number: 59, title: "The Secret of the Querent in a Chart" },
  { id: "if-she-he-loves-you-or-not", number: 60, title: "If She/He Loves You or Not" },
  { id: "if-a-marriage-is-good-or-not", number: 61, title: "If a Marriage Is Good or Not" },
  { id: "if-the-prayers-done-for-someone-have-been", number: 62, title: "If the Prayers Done for Someone Have Been Answered or Not" },
  { id: "if-the-lady-or-man-you-are-going", number: 63, title: "If the Lady or Man You Are Going to Marry Is Related to You by Family" },
  { id: "if-a-marriage-will-last-forever", number: 64, title: "If a Marriage Will Last Forever" },
  { id: "someone-s-behavior-also-see-chapter-forty-three", number: null, title: "Additional Method — Someone's Behavior (also see Chapter Forty-Three)" },
  { id: "if-a-partner-has-a-particular-disease-or", number: 65, title: "If a Partner Has a Particular Disease or Sickness" },
  { id: "if-someone-has-married-before-or-if-he", number: 66, title: "If Someone Has Married Before, or If He/She Is Married" },
  { id: "if-she-he-is-still-in-the-marriage", number: null, title: "Additional Method — If She/He Is Still in the Marriage or Not" },
  { id: "if-he-she-is-enjoying-the-marriage", number: 67, title: "If He/She Is Enjoying the Marriage" },
  { id: "if-your-partner-is-cheating-on-you", number: 68, title: "If Your Partner Is Cheating on You" },
  { id: "if-your-ex-husband-wife-will-re-marry", number: 69, title: "If Your Ex-Husband/Wife Will Re-Marry Again After the Divorce" },
  { id: "if-a-pregnant-woman-will-have-childbirth-problems", number: 70, title: "If a Pregnant Woman Will Have Childbirth Problems in Her Marriage" },
  { id: "if-a-man-will-have-manhood-problems-in", number: 71, title: "If a Man Will Have Manhood Problems in His Marriage or Life" },
  { id: "if-a-lady-or-man-has-feelings-for", number: 72, title: "If a Lady or Man Has Feelings for You or Not" },
  { id: "if-a-woman-has-married-more-than-one", number: 73, title: "If a Woman Has Married More Than One Man at the Same Time (Polyandry)" },
  { id: "if-someone-is-an-adulterous-son-daughter-born", number: 74, title: "If Someone Is an Adulterous Son/Daughter (Born Out of Wedlock)" },
  { id: "if-he-she-is-a-womanizer-or-a", number: 75, title: "If He/She Is a Womanizer or a Harlot" },
  { id: "if-your-ex-husband-wife-girlfriend-or-boyfriend", number: 76, title: "If Your Ex-Husband, Wife, Girlfriend, or Boyfriend Will Return or Not" },
  { id: "if-the-pregnancy-is-healthy-or-not", number: 77, title: "If the Pregnancy Is Healthy or Not" },
  { id: "the-number-of-months-of-a-pregnancy-how", number: 78, title: "The Number of Months of a Pregnancy (How Old Is the Pregnancy)" },
  { id: "the-number-of-babies-in-a-pregnancy", number: 79, title: "The Number of Babies in a Pregnancy" },
  { id: "if-a-pregnancy-is-yours-or-not-d", number: 80, title: "If a Pregnancy Is Yours or Not (D.N.A.)" },
  { id: "if-she-will-put-to-bed-peacefully-or", number: 81, title: "If She Will Put to Bed Peacefully or Not" },
  { id: "the-time-she-will-put-to-bed", number: 82, title: "The Time She Will Put to Bed" },
  { id: "if-it-s-day-or-night-that-she", number: 83, title: "If It's Day or Night That She Will Put to Bed" },
  { id: "if-your-enemy-is-from-your-father-s", number: 84, title: "If Your Enemy Is from Your Father's, Mother's, Wife's, Boyfriend's/Girlfriend's, or Your Friend's Family" },
  { id: "how-the-future-of-two-people-s-friendship", number: 85, title: "How the Future of Two People's Friendship Will Be" },
  { id: "secrets-between-two-friends-who-follow-each-other", number: null, title: "Additional Topic — Secrets Between Two Friends Who Follow Each Other in the Chart" },
  { id: "if-it-s-business-or-handwork-that-will", number: 86, title: "If It's Business or Handwork That Will Benefit You" },
  { id: "when-your-suffering-and-pain-or-sadness-will", number: 87, title: "When Your Suffering and Pain or Sadness Will End" },
  { id: "if-you-will-get-a-position-rank-or", number: 88, title: "If You Will Get a Position/Rank or Not" },
  { id: "if-your-success-or-wealth-will-remain-forever", number: 89, title: "If Your Success or Wealth Will Remain Forever or Not" },
  { id: "if-someone-s-misery-will-be-taken-away", number: 90, title: "If Someone's Misery Will Be Taken Away from Him/Her or Not" },
  { id: "if-something-is-present-past-or-future", number: 91, title: "If Something Is Present, Past, or Future" },
  { id: "the-ending-part-of-anything-you-want-to", number: 92, title: "The Ending Part of Anything You Want to Do in Your Life" },
  { id: "if-someone-has-long-life-or-not", number: 93, title: "If Someone Has Long Life or Not" },
  { id: "the-lifespan-and-when-someone-will-die", number: 94, title: "The Lifespan and When Someone Will Die" },
  { id: "the-stars-that-talk-about-your-youthful-time", number: 95, title: "The Stars That Talk About Your Youthful Time, Middle Age, and Old Age" },
  { id: "if-a-sick-person-has-long-life-or", number: 96, title: "If a Sick Person Has Long Life or Not" },
  { id: "if-a-sick-person-has-long-life-repeated", number: null, title: "Additional Method — If a Sick Person Has Long Life (repeated later in the notebook)" },
  { id: "where-one-will-die-place-of-death", number: 97, title: "Where One Will Die (Place of Death)" },
  { id: "the-causes-of-someone-s-death", number: 98, title: "The Causes of Someone's Death" },
  { id: "if-someone-or-something-good-will-come-to", number: 99, title: "If Someone or Something Good Will Come to You Today or Not" },
  { id: "if-today-is-a-good-day-or-not", number: 100, title: "If Today Is a Good Day or Not" },
  { id: "as-a-stranger-if-the-food-you-want", number: 101, title: "As a Stranger, If the Food You Want to Eat Is from the Market or Home-Prepared" },
  { id: "if-this-money-the-work-or-the-lady", number: 102, title: "If This Money, the Work, or the Lady/Husband Will Be Stable in Your Life" },
  { id: "if-the-querent-is-sick-or-not", number: 103, title: "If the Querent Is Sick or Not" },
  { id: "if-the-sickness-is-from-human-jinn-or", number: 104, title: "If the Sickness Is from Human, Jinn, or God Almighty" },
  { id: "if-a-sick-person-has-long-life-repeated-2", number: null, title: "Additional Method — If a Sick Person Has Long Life (repeated again in the notebook)" },
  { id: "which-part-of-the-body-is-paining-the", number: 105, title: "Which Part of the Body Is Paining the Sick Person" },
  { id: "parts-of-the-human-body-and-the-stars", number: 106, title: "Parts of the Human Body and the Stars Representing Them" },
  { id: "if-you-will-see-what-you-are-searching", number: 107, title: "If You Will See What You Are Searching For or Not (Nazir)" },
  { id: "if-you-will-get-to-talk-to-someone", number: 108, title: "If You Will Get to Talk to Someone, or If Conversation Will Take Place Between Two People" },
  { id: "if-you-will-get-what-you-are-searching", number: 118, title: "If You Will Get What You Are Searching For, in a Place (Itisal)" },
  { id: "if-you-won-t-get-what-you-are", number: 119, title: "If You Won't Get What You Are Searching For (Ifusal)" },
  { id: "if-you-have-enemies-and-how-many", number: 120, title: "If You Have Enemies and How Many" },
  { id: "if-you-will-get-knowledge-or-not-in", number: 121, title: "If You Will Get Knowledge or Not in Your Life" },
  { id: "if-you-will-get-what-you-want-or", number: 122, title: "If You Will Get What You Want, or If Your Intentions Will Be Gotten (Very Close) [Note: the Table of Contents lists this chapter's title as \"if someone has long life or not (sick person)\" — but the content found at this position in the manuscript body is about intentions/getting what you want, as given here. This appears to be a mismatch in the original notebook between its own Table of Contents and body, not a transcription error; the \"long life/sick person\" topic appears repeatedly elsewhere, in Chapters Ninety-Three, Ninety-Six, and as an additional method near Chapter Hundred and Four.]" },
  { id: "if-something-will-burn", number: 123, title: "If Something Will Burn" },
  { id: "if-something-has-really-been-stolen-or-not", number: 124, title: "If Something Has Really Been Stolen or Not" },
  { id: "if-they-will-return-a-stolen-thing-back", number: 125, title: "If They Will Return a Stolen Thing Back" },
  { id: "the-number-of-thieves", number: 126, title: "The Number of Thieves" },
  { id: "the-description-of-the-thief", number: 127, title: "The Description of the Thief" },
  { id: "if-the-thief-or-the-stolen-thing-is", number: 128, title: "If the Thief or the Stolen Thing Is in Town or Out of Town" },
  { id: "if-it-is-the-accused-person-that-stole", number: 129, title: "If It Is the Accused Person That Stole the Thing or Not" },
  { id: "the-thief-from-among-the-accused-people", number: 130, title: "The Thief from Among the Accused People" },
  { id: "if-something-was-buried-or-has-been-buried", number: 131, title: "If Something Was Buried, or Has Been Buried, in a Particular Place" },
  { id: "if-there-s-a-hidden-treasure-gold-money", number: 132, title: "If There's a Hidden Treasure (Gold/Money) in a Particular Place" },
  { id: "how-deep-something-is-buried", number: 133, title: "How Deep Something Is Buried" },
  { id: "where-a-traveller-has-travelled-to", number: 134, title: "Where a Traveller Has Travelled To" },
  { id: "if-the-traveller-has-travelled-by-air-water", number: 135, title: "If the Traveller Has Travelled by Air, Water, or Land" },
  { id: "if-the-traveller-has-reached-where-he-she", number: 136, title: "If the Traveller Has Reached Where He/She Is Going or Not" },
  { id: "if-someone-is-truthful-or-not", number: 137, title: "If Someone Is Truthful or Not" },
  { id: "if-a-prisoner-will-come-out-of-prison", number: 138, title: "If a Prisoner Will Come Out of Prison and How Long It Will Take" },
  { id: "if-the-prisoner-will-be-removed-peacefully", number: 139, title: "If the Prisoner Will Be Removed Peacefully" },
  { id: "how-long-the-prisoner-will-stay-in-prison", number: 140, title: "How Long the Prisoner Will Stay in Prison/Cells" },
  { id: "if-the-prisoner-is-male-or-female", number: 141, title: "If the Prisoner Is Male or Female" },
  { id: "where-kidnappers-are-keeping-a-person-hostage", number: 142, title: "Where Kidnappers Are Keeping a Person Hostage" },
  { id: "the-consequence-of-a-prisoner", number: 143, title: "The Consequence of a Prisoner" },
  { id: "if-you-will-get-your-debts-deposit-or", number: 144, title: "If You Will Get Your Debts, Deposit, or Savings Back" },
  { id: "if-someone-will-get-a-particular-position-or", number: 145, title: "If Someone Will Get a Particular Position or Chieftaincy Title" },
  { id: "if-you-will-own-a-house-in-your", number: 146, title: "If You Will Own a House in Your Life" },
  { id: "if-this-apartment-you-are-going-to-is", number: 147, title: "If This Apartment You Are Going to Is Safe/Good for You" },
  { id: "if-you-will-receive-the-expected-message", number: 148, title: "If You Will Receive the Expected Message" },
  { id: "which-day-a-pregnant-woman-will-put-to", number: 149, title: "Which Day a Pregnant Woman Will Put to Bed" },
  { id: "if-you-will-get-back-to-work-after", number: 150, title: "If You Will Get Back to Work After Getting a Problem in the Workplace" },
  { id: "dreams-and-their-interpretations", number: 151, title: "Dreams and Their Interpretations" },
];
