// INTERPRETATION BASIS PER ENGINE METHOD — which attribute each hand-authored
// method actually reads from its resulting figure.
//
// This records, per method id, the rule the method ALREADY applies in its own
// `evaluate` (see the question files). It changes no outcome and is not a
// scoring rule: it is a label so the UI can show the deciding attribute only.
// Nothing is inferred from the resulting figure, and there is no universal
// element ranking. Consistency with each method's evaluate source is guarded
// by lib/raml/interpretationBasis.test.ts.
import type { InterpretationBasis } from '@/lib/raml/interpretationBasis';

/** Rule asks whether the figure is good / middle-good / bad (± up/down). */
const STAR_QUALITY_METHODS: readonly string[] = [
  'business-method-1',
  'business-method-2',
  'business-method-3',
  'court-method-1',
  'court-method-2',
  'court-method-4',
  'stolen-method-4',
  'travel-method-1',
  'stay-in-place-method-1',
  'sickness-method-1',
  'rich-method-1',
  'children-method-1',
  'pregnancy-stable-method-1',
  'things-better-method-1',
  'overcome-enemy-method-2',
  'election-method-1',
  'election-method-2',
  'stay-house-method-1',
  'stay-house-method-2',
  'stay-town-method-1',
  'stay-town-method-2',
  'canoe-method-2',
  'enemies-working-method-2',
  'game-winner-method-1',
  'lovers-compatible-method-1',
  'lovers-compatible-method-2',
  'visitor-good-bad-method-1',
  'visitor-good-bad-method-2',
  'spiritual-work-method-1',
  'spiritual-work-method-2',
  'item-taker-method-2',
  'get-what-you-want-method-1',
  'get-what-you-want-method-2',
  'future-spouse-character-method-1',
  'lady-pregnant-method-4',
  'friendship-good-method-1',
  'does-love-you-method-1',
  'does-love-you-method-2',
  'marriage-good-method-1',
  'marriage-good-method-2',
  'marriage-last-forever-method-1',
  'enjoying-marriage-method-1',
  'ex-remarry-method-1',
  'feelings-for-you-method-1',
  'pregnancy-healthy-method-1',
  'pregnancy-healthy-method-2',
  'pregnancy-paternity-method-2',
  'put-to-bed-peacefully-method-1',
  'enemy-family-origin-method-1',
  'enemy-family-origin-method-2',
  'enemy-family-origin-method-3',
  'friendship-future-method-1',
  'friendship-secrets-method-1',
  'suffering-will-end-method-1',
  'position-or-rank-method-1',
  'wealth-permanence-method-1',
  'misery-taken-away-method-2',
  'ending-of-anything-method-1',
  'something-good-today-method-1',
  'today-good-day-method-1',
  'sickness-cause-method-1',
  'stolen-thing-returned-method-1',
  'something-buried-method-2',
  'truthful-or-not-method-1',
  'prisoner-come-out-method-1',
  'prisoner-come-out-method-2',
  'prisoner-removed-peacefully-method-1',
  'how-long-prisoner-stay-method-1',
  'prisoner-consequence-method-1',
  'prisoner-consequence-method-2',
  'debts-deposit-back-method-1',
  'get-position-or-chieftaincy-method-1',
  'own-house-in-life-method-1',
  'apartment-safe-for-you-method-1',
  'receive-expected-message-method-1',
  'back-to-work-after-problem-method-1',
  'stay-in-marriage-method-2',
  'friendship-consequence-method-1',
];

/** Rule reads the figure's element, an element's line state, or an element tally. */
const ELEMENT_METHODS: readonly string[] = [
  'money-method-1',
  'money-method-3',
  'travel-method-2',
  'marriage-method-3',
  'success-at-home-method-2',
  'children-method-2',
  'overcome-enemy-method-1',
  'wife-sex-method-2',
  'terrain-method-1',
  'armed-robbers-method-1',
  'success-where-going-method-1',
  'successful-trip-method-1',
  'lost-thief-location-method-1',
  'rain-method-4',
  'enemies-working-method-1',
  'locate-method-1',
  'get-lost-thing-back-method-1',
  'closer-or-far-method-1',
  'get-gold-method-1',
  'where-success-method-1',
  'travel-time-method-1',
  'couples-sex-method-1',
  'couples-sex-method-2',
  'prayers-answered-method-1',
  'ex-return-method-1',
  'ex-return-method-2',
  'time-to-put-to-bed-method-1',
  'sick-person-long-life-method-1',
  'sick-person-long-life-method-2',
  'querent-sick-method-1',
  'querent-sick-method-2',
  'something-will-burn-method-1',
  'traveller-mode-method-1',
];

/** Rule is the method's own: named figures, lists, found-in-chart, up/down alone, counts, positions. */
const SOURCE_SPECIFIC_METHODS: readonly string[] = [
  'money-method-2',
  'money-method-4',
  'court-method-3',
  'stolen-method-1',
  'stolen-method-2',
  'stolen-method-3',
  'travel-method-3',
  'hunting-method-1',
  'fight-war-location-method-1',
  'fight-war-location-method-2',
  'enemy-location-method-1',
  'marriage-method-1',
  'marriage-method-2',
  'marriage-method-4',
  'sickness-method-2',
  'sickness-method-3',
  'lost-around-method-1',
  'lost-around-method-2',
  'lost-around-method-3',
  'lost-around-method-4',
  'lost-around-method-5',
  'success-at-home-method-1',
  'children-method-3',
  'children-method-4',
  'children-method-5',
  'timing-method-1',
  'timing-method-2',
  'wife-sex-method-1',
  'wife-sex-method-3',
  'stay-house-method-3',
  'canoe-method-1',
  'fight-argument-method-1',
  'farming-method-1',
  'farming-method-2',
  'money-strangers-method-1',
  'rain-method-1',
  'rain-method-2',
  'rain-method-3',
  'family-doing-well-method-1',
  'game-winner-method-2',
  'item-taker-method-1',
  'proposal-accepted-method-1',
  'lady-pregnant-method-1',
  'lady-pregnant-method-2',
  'lady-pregnant-method-3',
  'child-gender-method-1',
  'child-gender-method-2',
  'child-gender-method-3',
  'yearly-news-method-1',
  'asking-about-method-1',
  'thief-whereabouts-method-1',
  'related-by-family-method-1',
  'marriage-last-forever-method-2',
  'partner-disease-method-1',
  'partner-disease-method-2',
  'partner-disease-method-3',
  'married-before-method-1',
  'still-in-marriage-method-1',
  'partner-cheating-method-1',
  'childbirth-problems-method-1',
  'childbirth-problems-method-2',
  'manhood-problems-method-1',
  'manhood-problems-method-2',
  'polyandry-method-1',
  'born-out-of-wedlock-method-1',
  'womanizer-method-1',
  'pregnancy-months-method-1',
  'number-of-babies-method-1',
  'number-of-babies-method-2',
  'pregnancy-paternity-method-1',
  'time-to-put-to-bed-method-2',
  'day-or-night-birth-method-1',
  'friendship-future-method-2',
  'business-or-handwork-method-1',
  'business-or-handwork-method-2',
  'misery-taken-away-method-1',
  'present-past-future-method-1',
  'long-life-method-1',
  'lifespan-when-death-method-1',
  'place-of-death-method-1',
  'causes-of-death-method-1',
  'food-market-or-home-method-1',
  'money-work-lady-stable-method-1',
  'body-part-in-pain-method-1',
  'see-what-searching-for-method-1',
  'conversation-will-happen-method-1',
  'get-what-searching-for-in-place-method-1',
  'what-blocks-you-method-1',
  'enemies-how-many-method-1',
  'enemies-how-many-method-2',
  'get-knowledge-in-life-method-1',
  'get-what-you-want-very-close-method-1-direction',
  'get-what-you-want-very-close-method-1-stability',
  'get-what-you-want-very-close-method-2-direction',
  'get-what-you-want-very-close-method-2-stability',
  'something-really-stolen-method-1',
  'something-really-stolen-method-2',
  'number-of-thieves-method-1',
  'thief-description-method-1',
  'thief-description-method-2',
  'thief-in-town-or-out-method-1',
  'accused-person-guilty-method-1-direction',
  'accused-person-guilty-method-1-stability',
  'thief-among-accused-method-1-direction',
  'thief-among-accused-method-1-stability',
  'thief-among-accused-method-2',
  'something-buried-method-1',
  'something-buried-method-3',
  'hidden-treasure-method-1',
  'hidden-treasure-method-2',
  'hidden-treasure-method-3-direction',
  'hidden-treasure-method-3-stability',
  'how-deep-buried-method-1',
  'traveller-destination-method-1',
  'traveller-reached-destination-method-1',
  'truthful-or-not-method-2',
  'prisoner-male-or-female-method-1',
  'kidnapper-location-method-1',
  'pregnant-woman-put-to-bed-day-method-1',
  'stay-in-marriage-method-1',
  'dreams-interpretation-method-1',
  'gift-visitor-figures-method-1',
];

const BASIS_BY_METHOD: ReadonlyMap<string, InterpretationBasis> = new Map<string, InterpretationBasis>([
  ...STAR_QUALITY_METHODS.map((id): [string, InterpretationBasis] => [id, 'star_quality']),
  ...ELEMENT_METHODS.map((id): [string, InterpretationBasis] => [id, 'element']),
  ...SOURCE_SPECIFIC_METHODS.map((id): [string, InterpretationBasis] => [id, 'source_specific']),
]);

/** The basis a method rests its answer on, or null for an unknown method id. */
export function interpretationBasisForMethod(methodId: string): InterpretationBasis | null {
  return BASIS_BY_METHOD.get(methodId) ?? null;
}

export const METHOD_BASIS_LISTS = { STAR_QUALITY_METHODS, ELEMENT_METHODS, SOURCE_SPECIFIC_METHODS } as const;
