// Public question/method metadata (Prompt 27C — server-side reading execution
// migration). Generated once from lib/raml/engine/questions/index.ts's own
// QUESTION_REGISTRY — id/title/category/chapter/method status only. Never
// includes a method's source.quote (the verbatim protected sentence) or its
// calculate()/evaluate() functions, so this file is safe for any
// client-reachable code (the question catalogue/picker, offline URL
// enumeration, practicable-method eligibility) without pulling the full
// engine — and therefore every question's embedded source text — into the
// client bundle. The actual computation (and the source quote a user is
// actually authorized to see) now comes from the server reading/practice
// routes — see lib/server/raml/readingService.ts.

export interface PublicMethodMeta {
  id: string;
  label: string;
  status: 'verified' | 'needs_review' | 'uncertain';
  sourceBook: 'kanzul-mikban' | 'master-of-geomancy-vol-1';
  sourceChapterId: string;
}

export interface PublicQuestionMeta {
  id: string;
  title: string;
  categoryId: string;
  chapterId: string;
  resultKind: 'outcome' | 'descriptive' | null;
  methods: PublicMethodMeta[];
}

export const QUESTION_REGISTRY_META: Record<string, PublicQuestionMeta> = {
  "if-you-want-to-know-if-you-will": {
    id: "if-you-want-to-know-if-you-will",
    title: "Will I get money today?",
    categoryId: "money-possessions",
    chapterId: "if-you-want-to-know-if-you-will",
    resultKind: null,
    methods: [{ id: "money-method-1", label: "Method 1", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "if-you-want-to-know-if-you-will" }, { id: "money-method-2", label: "Method 2", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "if-you-want-to-know-if-you-will" }, { id: "money-method-3", label: "Method 3", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "if-you-want-to-know-if-you-will" }, { id: "money-method-4", label: "Method 4", status: "uncertain", sourceBook: "kanzul-mikban", sourceChapterId: "if-you-want-to-know-if-you-will" }],
  },
  "business-profit-and-loss": {
    id: "business-profit-and-loss",
    title: "Business, profit, and loss",
    categoryId: "money-possessions",
    chapterId: "business-profit-and-loss",
    resultKind: null,
    methods: [{ id: "business-method-1", label: "Method 1", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "business-profit-and-loss" }, { id: "business-method-2", label: "Method 2", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "business-profit-and-loss" }, { id: "business-method-3", label: "Method 3", status: "needs_review", sourceBook: "kanzul-mikban", sourceChapterId: "business-profit-and-loss" }],
  },
  "if-you-will-win-a-case-in-court": {
    id: "if-you-will-win-a-case-in-court",
    title: "Will I win a fight, war, or court case?",
    categoryId: "legal-conflict",
    chapterId: "if-you-will-win-a-case-in-court",
    resultKind: null,
    methods: [{ id: "court-method-1", label: "Method 1", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "if-you-will-win-a-case-in-court" }, { id: "court-method-2", label: "Method 2", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "if-you-will-win-a-case-in-court" }, { id: "court-method-3", label: "Method 3", status: "uncertain", sourceBook: "kanzul-mikban", sourceChapterId: "if-you-will-win-a-case-in-court" }, { id: "court-method-4", label: "Method 4", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "if-you-will-win-a-case-in-court" }],
  },
  "if-you-will-get-your-stolen-things-back": {
    id: "if-you-will-get-your-stolen-things-back",
    title: "Will I get my stolen or lost things back?",
    categoryId: "lost-stolen",
    chapterId: "if-you-will-get-your-stolen-things-back",
    resultKind: null,
    methods: [{ id: "stolen-method-1", label: "Method 1 (Part B)", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "if-you-will-get-your-stolen-things-back" }, { id: "stolen-method-2", label: "Method 2 (Part B)", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "if-you-will-get-your-stolen-things-back" }, { id: "stolen-method-3", label: "Method 3 (Part B)", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "if-you-will-get-your-stolen-things-back" }, { id: "stolen-method-4", label: "Method 4 (Part B, \"some scholars\")", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "if-you-will-get-your-stolen-things-back" }],
  },
  "traveling-business-and-if-you-will-return-from": {
    id: "traveling-business-and-if-you-will-return-from",
    title: "Will I return safely from a trip?",
    categoryId: "travel-change",
    chapterId: "traveling-business-and-if-you-will-return-from",
    resultKind: null,
    methods: [{ id: "travel-method-1", label: "Method 1", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "traveling-business-and-if-you-will-return-from" }, { id: "travel-method-2", label: "Method 2", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "traveling-business-and-if-you-will-return-from" }, { id: "travel-method-3", label: "Method 3", status: "needs_review", sourceBook: "kanzul-mikban", sourceChapterId: "traveling-business-and-if-you-will-return-from" }],
  },
  "hunting-in-water-and-on-land-and-searching": {
    id: "hunting-in-water-and-on-land-and-searching",
    title: "Will my search or hunt succeed?",
    categoryId: "lost-stolen",
    chapterId: "hunting-in-water-and-on-land-and-searching",
    resultKind: null,
    methods: [{ id: "hunting-method-1", label: "Method 1", status: "uncertain", sourceBook: "kanzul-mikban", sourceChapterId: "hunting-in-water-and-on-land-and-searching" }],
  },
  "if-you-will-win-a-fight-war-or": {
    id: "if-you-will-win-a-fight-war-or",
    title: "Will I win a fight, war, or court case? (H6/H1+H8 method)",
    categoryId: "legal-conflict",
    chapterId: "if-you-will-win-a-fight-war-or",
    resultKind: null,
    methods: [{ id: "fight-war-location-method-1", label: "Method 1", status: "uncertain", sourceBook: "kanzul-mikban", sourceChapterId: "if-you-will-win-a-fight-war-or" }, { id: "fight-war-location-method-2", label: "Method 2", status: "uncertain", sourceBook: "kanzul-mikban", sourceChapterId: "if-you-will-win-a-fight-war-or" }],
  },
  "if-you-want-to-know-where-your-enemy": {
    id: "if-you-want-to-know-where-your-enemy",
    title: "Where is my enemy or a thief hiding?",
    categoryId: "legal-conflict",
    chapterId: "if-you-want-to-know-where-your-enemy",
    resultKind: null,
    methods: [{ id: "enemy-location-method-1", label: "Method 1", status: "uncertain", sourceBook: "kanzul-mikban", sourceChapterId: "if-you-want-to-know-where-your-enemy" }],
  },
  "marriage-and-its-blessings": {
    id: "marriage-and-its-blessings",
    title: "Marriage and its blessings",
    categoryId: "love-couple",
    chapterId: "marriage-and-its-blessings",
    resultKind: null,
    methods: [{ id: "marriage-method-1", label: "Method 1", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "marriage-and-its-blessings" }, { id: "marriage-method-2", label: "Method 2", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "marriage-and-its-blessings" }, { id: "marriage-method-3", label: "Method 3", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "marriage-and-its-blessings" }, { id: "marriage-method-4", label: "Method 4", status: "uncertain", sourceBook: "kanzul-mikban", sourceChapterId: "marriage-and-its-blessings" }],
  },
  "if-one-will-stay-in-a-particular-place": {
    id: "if-one-will-stay-in-a-particular-place",
    title: "Will they stay in a particular place, and is it good?",
    categoryId: "travel-change",
    chapterId: "if-one-will-stay-in-a-particular-place",
    resultKind: null,
    methods: [{ id: "stay-in-place-method-1", label: "Method 1", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "if-one-will-stay-in-a-particular-place" }],
  },
  "sickness-if-he-she-will-survive": {
    id: "sickness-if-he-she-will-survive",
    title: "Sickness \u2014 will he/she survive?",
    categoryId: "health-hardships",
    chapterId: "sickness-if-he-she-will-survive",
    resultKind: null,
    methods: [{ id: "sickness-method-1", label: "Method 1", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "sickness-if-he-she-will-survive" }, { id: "sickness-method-2", label: "Method 2", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "sickness-if-he-she-will-survive" }, { id: "sickness-method-3", label: "Method 3", status: "uncertain", sourceBook: "kanzul-mikban", sourceChapterId: "sickness-if-he-she-will-survive" }],
  },
  "if-your-lost-thing-is-still-around-or": {
    id: "if-your-lost-thing-is-still-around-or",
    title: "Is my lost thing still around, or gone?",
    categoryId: "lost-stolen",
    chapterId: "if-your-lost-thing-is-still-around-or",
    resultKind: null,
    methods: [{ id: "lost-around-method-1", label: "Method 1", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "if-your-lost-thing-is-still-around-or" }, { id: "lost-around-method-2", label: "Method 2", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "if-your-lost-thing-is-still-around-or" }, { id: "lost-around-method-3", label: "Method 3", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "if-your-lost-thing-is-still-around-or" }, { id: "lost-around-method-4", label: "Method 4", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "if-your-lost-thing-is-still-around-or" }, { id: "lost-around-method-5", label: "Method 5", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "if-your-lost-thing-is-still-around-or" }],
  },
  "if-you-want-to-know-if-you-will-2": {
    id: "if-you-want-to-know-if-you-will-2",
    title: "Will I succeed at home, or do I need to travel away?",
    categoryId: "travel-change",
    chapterId: "if-you-want-to-know-if-you-will-2",
    resultKind: null,
    methods: [{ id: "success-at-home-method-1", label: "Method 1", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "if-you-want-to-know-if-you-will-2" }, { id: "success-at-home-method-2", label: "Method 2", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "if-you-want-to-know-if-you-will-2" }],
  },
  "if-you-want-to-know-if-you-will-3": {
    id: "if-you-want-to-know-if-you-will-3",
    title: "Will I be rich in life?",
    categoryId: "money-possessions",
    chapterId: "if-you-want-to-know-if-you-will-3",
    resultKind: null,
    methods: [{ id: "rich-method-1", label: "Method 1", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "if-you-want-to-know-if-you-will-3" }],
  },
  "if-you-will-get-children-from-a-lady": {
    id: "if-you-will-get-children-from-a-lady",
    title: "Will I get children from this lady?",
    categoryId: "love-couple",
    chapterId: "if-you-will-get-children-from-a-lady",
    resultKind: null,
    methods: [{ id: "children-method-1", label: "Method 1", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "if-you-will-get-children-from-a-lady" }, { id: "children-method-2", label: "Method 2", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "if-you-will-get-children-from-a-lady" }, { id: "children-method-3", label: "Method 3", status: "uncertain", sourceBook: "kanzul-mikban", sourceChapterId: "if-you-will-get-children-from-a-lady" }, { id: "children-method-4", label: "Method 4", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "if-you-will-get-children-from-a-lady" }, { id: "children-method-5", label: "Method 5", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "if-you-will-get-children-from-a-lady" }],
  },
  "if-a-pregnancy-is-going-to-be-stable": {
    id: "if-a-pregnancy-is-going-to-be-stable",
    title: "Is this pregnancy going to be stable?",
    categoryId: "family-loved-ones",
    chapterId: "if-a-pregnancy-is-going-to-be-stable",
    resultKind: null,
    methods: [{ id: "pregnancy-stable-method-1", label: "Method 1", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "if-a-pregnancy-is-going-to-be-stable" }],
  },
  "if-things-will-be-better-for-the-questioner": {
    id: "if-things-will-be-better-for-the-questioner",
    title: "Will things get better for me?",
    categoryId: "fate-timing",
    chapterId: "if-things-will-be-better-for-the-questioner",
    resultKind: null,
    methods: [{ id: "things-better-method-1", label: "Method 1", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "if-things-will-be-better-for-the-questioner" }],
  },
  "if-you-will-overcome-your-enemy-or-not": {
    id: "if-you-will-overcome-your-enemy-or-not",
    title: "Will I overcome my enemy?",
    categoryId: "legal-conflict",
    chapterId: "if-you-will-overcome-your-enemy-or-not",
    resultKind: null,
    methods: [{ id: "overcome-enemy-method-1", label: "Method 1", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "if-you-will-overcome-your-enemy-or-not" }, { id: "overcome-enemy-method-2", label: "Method 2", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "if-you-will-overcome-your-enemy-or-not" }],
  },
  "if-something-will-happen-in-an-hour-day": {
    id: "if-something-will-happen-in-an-hour-day",
    title: "When will this happen?",
    categoryId: "fate-timing",
    chapterId: "if-something-will-happen-in-an-hour-day",
    resultKind: null,
    methods: [{ id: "timing-method-1", label: "Method 1", status: "uncertain", sourceBook: "kanzul-mikban", sourceChapterId: "if-something-will-happen-in-an-hour-day" }, { id: "timing-method-2", label: "Method 2", status: "uncertain", sourceBook: "kanzul-mikban", sourceChapterId: "if-something-will-happen-in-an-hour-day" }],
  },
  "who-will-win-an-election-or-a-chieftaincy": {
    id: "who-will-win-an-election-or-a-chieftaincy",
    title: "Who will win an election or a chieftaincy title?",
    categoryId: "work-success",
    chapterId: "who-will-win-an-election-or-a-chieftaincy",
    resultKind: null,
    methods: [{ id: "election-method-1", label: "Method 1", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "who-will-win-an-election-or-a-chieftaincy" }, { id: "election-method-2", label: "Method 2", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "who-will-win-an-election-or-a-chieftaincy" }],
  },
  "if-your-wife-or-sister-has-had-sex": {
    id: "if-your-wife-or-sister-has-had-sex",
    title: "Has my wife or sister had sex?",
    categoryId: "love-couple",
    chapterId: "if-your-wife-or-sister-has-had-sex",
    resultKind: "descriptive",
    methods: [{ id: "wife-sex-method-1", label: "Method 1", status: "needs_review", sourceBook: "kanzul-mikban", sourceChapterId: "if-your-wife-or-sister-has-had-sex" }, { id: "wife-sex-method-2", label: "Method 2", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "if-your-wife-or-sister-has-had-sex" }, { id: "wife-sex-method-3", label: "Method 3", status: "uncertain", sourceBook: "kanzul-mikban", sourceChapterId: "if-your-wife-or-sister-has-had-sex" }],
  },
  "if-it-s-good-to-stay-in-a": {
    id: "if-it-s-good-to-stay-in-a",
    title: "Is it good to stay in this house?",
    categoryId: "travel-change",
    chapterId: "if-it-s-good-to-stay-in-a",
    resultKind: null,
    methods: [{ id: "stay-house-method-1", label: "Method 1", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "if-it-s-good-to-stay-in-a" }, { id: "stay-house-method-2", label: "Method 2", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "if-it-s-good-to-stay-in-a" }, { id: "stay-house-method-3", label: "Method 3", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "if-it-s-good-to-stay-in-a" }],
  },
  "if-it-s-good-to-stay-in-a-2": {
    id: "if-it-s-good-to-stay-in-a-2",
    title: "Is it good to stay in this town?",
    categoryId: "travel-change",
    chapterId: "if-it-s-good-to-stay-in-a-2",
    resultKind: null,
    methods: [{ id: "stay-town-method-1", label: "Method 1", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "if-it-s-good-to-stay-in-a-2" }, { id: "stay-town-method-2", label: "Method 2", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "if-it-s-good-to-stay-in-a-2" }],
  },
  "is-there-much-trees-water-sand-or-stones": {
    id: "is-there-much-trees-water-sand-or-stones",
    title: "Is there much trees, water, sand, or stones where I am going?",
    categoryId: "travel-change",
    chapterId: "is-there-much-trees-water-sand-or-stones",
    resultKind: "descriptive",
    methods: [{ id: "terrain-method-1", label: "Method 1", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "is-there-much-trees-water-sand-or-stones" }],
  },
  "if-you-will-be-safe-entering-a-canoe": {
    id: "if-you-will-be-safe-entering-a-canoe",
    title: "Will I be safe entering a canoe, or get fish from fishing?",
    categoryId: "travel-change",
    chapterId: "if-you-will-be-safe-entering-a-canoe",
    resultKind: null,
    methods: [{ id: "canoe-method-1", label: "Method 1", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "if-you-will-be-safe-entering-a-canoe" }, { id: "canoe-method-2", label: "Method 2", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "if-you-will-be-safe-entering-a-canoe" }],
  },
  "if-there-are-armed-robbers-on-your-way": {
    id: "if-there-are-armed-robbers-on-your-way",
    title: "Are there armed robbers on my way?",
    categoryId: "legal-conflict",
    chapterId: "if-there-are-armed-robbers-on-your-way",
    resultKind: null,
    methods: [{ id: "armed-robbers-method-1", label: "Method 1", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "if-there-are-armed-robbers-on-your-way" }],
  },
  "if-there-will-be-a-fight-argument-etc": {
    id: "if-there-will-be-a-fight-argument-etc",
    title: "Will there be a fight or argument?",
    categoryId: "legal-conflict",
    chapterId: "if-there-will-be-a-fight-argument-etc",
    resultKind: null,
    methods: [{ id: "fight-argument-method-1", label: "Method 1", status: "uncertain", sourceBook: "kanzul-mikban", sourceChapterId: "if-there-will-be-a-fight-argument-etc" }],
  },
  "about-farming-and-food-in-the-year": {
    id: "about-farming-and-food-in-the-year",
    title: "How will farming and food be this year?",
    categoryId: "work-success",
    chapterId: "about-farming-and-food-in-the-year",
    resultKind: null,
    methods: [{ id: "farming-method-1", label: "Method 1 (harvest by direction)", status: "uncertain", sourceBook: "kanzul-mikban", sourceChapterId: "about-farming-and-food-in-the-year" }, { id: "farming-method-2", label: "Method 2 (general harvest/calamity)", status: "uncertain", sourceBook: "kanzul-mikban", sourceChapterId: "about-farming-and-food-in-the-year" }],
  },
  "if-you-will-get-money-or-good-strangers": {
    id: "if-you-will-get-money-or-good-strangers",
    title: "Will I get money or good strangers today?",
    categoryId: "money-possessions",
    chapterId: "if-you-will-get-money-or-good-strangers",
    resultKind: null,
    methods: [{ id: "money-strangers-method-1", label: "Method 1", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "if-you-will-get-money-or-good-strangers" }],
  },
  "if-you-will-be-successful-where-you-are": {
    id: "if-you-will-be-successful-where-you-are",
    title: "Will I be successful where I am going?",
    categoryId: "work-success",
    chapterId: "if-you-will-be-successful-where-you-are",
    resultKind: null,
    methods: [{ id: "success-where-going-method-1", label: "Method 1", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "if-you-will-be-successful-where-you-are" }],
  },
  "if-you-will-be-successful-and-get-what": {
    id: "if-you-will-be-successful-and-get-what",
    title: "Will I be successful and get what I want from this trip?",
    categoryId: "travel-change",
    chapterId: "if-you-will-be-successful-and-get-what",
    resultKind: null,
    methods: [{ id: "successful-trip-method-1", label: "Method 1", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "if-you-will-be-successful-and-get-what" }],
  },
  "about-a-lost-thing-stolen-things": {
    id: "about-a-lost-thing-stolen-things",
    title: "Where is my lost or stolen thing, and who took it?",
    categoryId: "lost-stolen",
    chapterId: "about-a-lost-thing-stolen-things",
    resultKind: "descriptive",
    methods: [{ id: "lost-thief-location-method-1", label: "Method 1", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "about-a-lost-thing-stolen-things" }],
  },
  "if-it-will-rain-today-or-not": {
    id: "if-it-will-rain-today-or-not",
    title: "Will it rain today?",
    categoryId: "fate-timing",
    chapterId: "if-it-will-rain-today-or-not",
    resultKind: null,
    methods: [{ id: "rain-method-1", label: "Method 1", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "if-it-will-rain-today-or-not" }, { id: "rain-method-2", label: "Method 2", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "if-it-will-rain-today-or-not" }, { id: "rain-method-3", label: "Method 3", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "if-it-will-rain-today-or-not" }, { id: "rain-method-4", label: "Method 4", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "if-it-will-rain-today-or-not" }],
  },
  "if-your-enemies-are-working-against-you-or": {
    id: "if-your-enemies-are-working-against-you-or",
    title: "Are my enemies working against me?",
    categoryId: "legal-conflict",
    chapterId: "if-your-enemies-are-working-against-you-or",
    resultKind: null,
    methods: [{ id: "enemies-working-method-1", label: "Method 1", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "if-your-enemies-are-working-against-you-or" }, { id: "enemies-working-method-2", label: "Method 2", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "if-your-enemies-are-working-against-you-or" }],
  },
  "if-your-family-is-doing-well-while-you": {
    id: "if-your-family-is-doing-well-while-you",
    title: "Is my family doing well while I am away?",
    categoryId: "family-loved-ones",
    chapterId: "if-your-family-is-doing-well-while-you",
    resultKind: null,
    methods: [{ id: "family-doing-well-method-1", label: "Method 1", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "if-your-family-is-doing-well-while-you" }],
  },
  "if-you-want-to-locate-someone-or-something": {
    id: "if-you-want-to-locate-someone-or-something",
    title: "Where can I locate this person or thing?",
    categoryId: "lost-stolen",
    chapterId: "if-you-want-to-locate-someone-or-something",
    resultKind: "descriptive",
    methods: [{ id: "locate-method-1", label: "Method 1", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "if-you-want-to-locate-someone-or-something" }],
  },
  "how-to-predict-a-game-who-will-win": {
    id: "how-to-predict-a-game-who-will-win",
    title: "Who will win this game?",
    categoryId: "fate-timing",
    chapterId: "how-to-predict-a-game-who-will-win",
    resultKind: null,
    methods: [{ id: "game-winner-method-1", label: "Method 1", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "how-to-predict-a-game-who-will-win" }, { id: "game-winner-method-2", label: "Method 2", status: "uncertain", sourceBook: "kanzul-mikban", sourceChapterId: "how-to-predict-a-game-who-will-win" }],
  },
  "if-two-lovers-will-be-compatible-for-marriage": {
    id: "if-two-lovers-will-be-compatible-for-marriage",
    title: "Will these two lovers be compatible for marriage?",
    categoryId: "love-couple",
    chapterId: "if-two-lovers-will-be-compatible-for-marriage",
    resultKind: null,
    methods: [{ id: "lovers-compatible-method-1", label: "Method 1", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "if-two-lovers-will-be-compatible-for-marriage" }, { id: "lovers-compatible-method-2", label: "Method 2", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "if-two-lovers-will-be-compatible-for-marriage" }],
  },
  "if-your-visitor-or-the-person-that-comes": {
    id: "if-your-visitor-or-the-person-that-comes",
    title: "Is my visitor a good or bad person?",
    categoryId: "fate-timing",
    chapterId: "if-your-visitor-or-the-person-that-comes",
    resultKind: null,
    methods: [{ id: "visitor-good-bad-method-1", label: "Method 1", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "if-your-visitor-or-the-person-that-comes" }, { id: "visitor-good-bad-method-2", label: "Method 2", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "if-your-visitor-or-the-person-that-comes" }],
  },
  "if-spiritual-work-you-want-to-do-for": {
    id: "if-spiritual-work-you-want-to-do-for",
    title: "Will this spiritual work I want to do for someone work?",
    categoryId: "fate-timing",
    chapterId: "if-spiritual-work-you-want-to-do-for",
    resultKind: null,
    methods: [{ id: "spiritual-work-method-1", label: "Method 1", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "if-spiritual-work-you-want-to-do-for" }, { id: "spiritual-work-method-2", label: "Method 2", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "if-spiritual-work-you-want-to-do-for" }],
  },
  "the-person-that-took-an-item-stole-something": {
    id: "the-person-that-took-an-item-stole-something",
    title: "Who took it, and will I get it back?",
    categoryId: "lost-stolen",
    chapterId: "the-person-that-took-an-item-stole-something",
    resultKind: null,
    methods: [{ id: "item-taker-method-1", label: "Method 1", status: "needs_review", sourceBook: "kanzul-mikban", sourceChapterId: "the-person-that-took-an-item-stole-something" }, { id: "item-taker-method-2", label: "Method 2", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "the-person-that-took-an-item-stole-something" }],
  },
  "if-you-will-get-what-you-want-from": {
    id: "if-you-will-get-what-you-want-from",
    title: "Will I get what I want from where I am going?",
    categoryId: "fate-timing",
    chapterId: "if-you-will-get-what-you-want-from",
    resultKind: null,
    methods: [{ id: "get-what-you-want-method-1", label: "Method 1", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "if-you-will-get-what-you-want-from" }, { id: "get-what-you-want-method-2", label: "Method 2", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "if-you-will-get-what-you-want-from" }],
  },
  "the-real-behavior-character-or-life-of-someone": {
    id: "the-real-behavior-character-or-life-of-someone",
    title: "What is the real behavior or character of the person I want to marry?",
    categoryId: "love-couple",
    chapterId: "the-real-behavior-character-or-life-of-someone",
    resultKind: null,
    methods: [{ id: "future-spouse-character-method-1", label: "Method 1", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "the-real-behavior-character-or-life-of-someone" }],
  },
  "if-a-lady-or-man-will-accept-your": {
    id: "if-a-lady-or-man-will-accept-your",
    title: "Will they accept my love proposal?",
    categoryId: "love-couple",
    chapterId: "if-a-lady-or-man-will-accept-your",
    resultKind: null,
    methods: [{ id: "proposal-accepted-method-1", label: "Method 1", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "if-a-lady-or-man-will-accept-your" }],
  },
  "if-you-will-get-the-lost-thing-back": {
    id: "if-you-will-get-the-lost-thing-back",
    title: "Will I get the lost thing back?",
    categoryId: "lost-stolen",
    chapterId: "if-you-will-get-the-lost-thing-back",
    resultKind: null,
    methods: [{ id: "get-lost-thing-back-method-1", label: "Method 1", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "if-you-will-get-the-lost-thing-back" }],
  },
  "if-a-lady-is-pregnant-or-not": {
    id: "if-a-lady-is-pregnant-or-not",
    title: "Is she pregnant?",
    categoryId: "family-loved-ones",
    chapterId: "if-a-lady-is-pregnant-or-not",
    resultKind: "descriptive",
    methods: [{ id: "lady-pregnant-method-1", label: "Method 1", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "if-a-lady-is-pregnant-or-not" }, { id: "lady-pregnant-method-2", label: "Method 2", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "if-a-lady-is-pregnant-or-not" }, { id: "lady-pregnant-method-3", label: "Method 3", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "s-if-you-want-to-know-if-she" }, { id: "lady-pregnant-method-4", label: "Method 4", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "s-if-you-want-to-know-if-she" }],
  },
  "if-it-s-a-male-or-female-child": {
    id: "if-it-s-a-male-or-female-child",
    title: "Will it be a male or female child?",
    categoryId: "family-loved-ones",
    chapterId: "if-it-s-a-male-or-female-child",
    resultKind: "descriptive",
    methods: [{ id: "child-gender-method-1", label: "Method 1", status: "needs_review", sourceBook: "kanzul-mikban", sourceChapterId: "if-it-s-a-male-or-female-child" }, { id: "child-gender-method-2", label: "Method 2", status: "needs_review", sourceBook: "kanzul-mikban", sourceChapterId: "if-it-s-a-male-or-female-child" }, { id: "child-gender-method-3", label: "Method 3", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "about-a-pregnancy-if-it-s-a-boy" }],
  },
  "if-something-is-closer-to-you-or-far": {
    id: "if-something-is-closer-to-you-or-far",
    title: "Is it closer to me or far away?",
    categoryId: "fate-timing",
    chapterId: "if-something-is-closer-to-you-or-far",
    resultKind: "descriptive",
    methods: [{ id: "closer-or-far-method-1", label: "Method 1", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "if-something-is-closer-to-you-or-far" }],
  },
  "if-you-will-get-gold-in-a-place": {
    id: "if-you-will-get-gold-in-a-place",
    title: "Will I get gold where I am working?",
    categoryId: "money-possessions",
    chapterId: "if-you-will-get-gold-in-a-place",
    resultKind: null,
    methods: [{ id: "get-gold-method-1", label: "Method 1", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "if-you-will-get-gold-in-a-place" }],
  },
  "if-things-are-going-to-be-well-this": {
    id: "if-things-are-going-to-be-well-this",
    title: "Will things go well for me this year?",
    categoryId: "fate-timing",
    chapterId: "if-things-are-going-to-be-well-this",
    resultKind: null,
    methods: [{ id: "yearly-news-method-1", label: "Method 1", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "if-things-are-going-to-be-well-this" }],
  },
  "the-friendship-between-two-people-if-it-s": {
    id: "the-friendship-between-two-people-if-it-s",
    title: "Is this friendship good?",
    categoryId: "family-loved-ones",
    chapterId: "the-friendship-between-two-people-if-it-s",
    resultKind: null,
    methods: [{ id: "friendship-good-method-1", label: "Method 1", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "the-friendship-between-two-people-if-it-s" }],
  },
  "if-a-querent-is-asking-about-someone-or": {
    id: "if-a-querent-is-asking-about-someone-or",
    title: "Am I asking about myself or someone else?",
    categoryId: "fate-timing",
    chapterId: "if-a-querent-is-asking-about-someone-or",
    resultKind: "descriptive",
    methods: [{ id: "asking-about-method-1", label: "Method 1", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "if-a-querent-is-asking-about-someone-or" }],
  },
  "where-your-success-is-or-where-you-will": {
    id: "where-your-success-is-or-where-you-will",
    title: "Where will I find success in life?",
    categoryId: "work-success",
    chapterId: "where-your-success-is-or-where-you-will",
    resultKind: "descriptive",
    methods: [{ id: "where-success-method-1", label: "Method 1", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "where-your-success-is-or-where-you-will" }],
  },
  "the-whereabouts-of-a-thief-or-robbers": {
    id: "the-whereabouts-of-a-thief-or-robbers",
    title: "Where is the thief or robbers?",
    categoryId: "legal-conflict",
    chapterId: "the-whereabouts-of-a-thief-or-robbers",
    resultKind: "descriptive",
    methods: [{ id: "thief-whereabouts-method-1", label: "Method 1", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "the-whereabouts-of-a-thief-or-robbers" }],
  },
  "when-to-travel-daytime-or-night-time": {
    id: "when-to-travel-daytime-or-night-time",
    title: "Should I travel during the day or at night?",
    categoryId: "travel-change",
    chapterId: "when-to-travel-daytime-or-night-time",
    resultKind: "descriptive",
    methods: [{ id: "travel-time-method-1", label: "Method 1", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "when-to-travel-daytime-or-night-time" }],
  },
  "if-couples-have-had-sex-or-not": {
    id: "if-couples-have-had-sex-or-not",
    title: "Have they had sex?",
    categoryId: "love-couple",
    chapterId: "if-couples-have-had-sex-or-not",
    resultKind: "descriptive",
    methods: [{ id: "couples-sex-method-1", label: "Method 1", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "if-couples-have-had-sex-or-not" }, { id: "couples-sex-method-2", label: "Method 2", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "if-couples-have-had-sex-or-not" }],
  },
  "if-she-he-loves-you-or-not": {
    id: "if-she-he-loves-you-or-not",
    title: "Does he/she love me?",
    categoryId: "love-couple",
    chapterId: "if-she-he-loves-you-or-not",
    resultKind: null,
    methods: [{ id: "does-love-you-method-1", label: "Method 1", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "if-she-he-loves-you-or-not" }, { id: "does-love-you-method-2", label: "Method 2", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "if-she-he-loves-you-or-not" }],
  },
  "if-a-marriage-is-good-or-not": {
    id: "if-a-marriage-is-good-or-not",
    title: "Is this marriage good?",
    categoryId: "love-couple",
    chapterId: "if-a-marriage-is-good-or-not",
    resultKind: null,
    methods: [{ id: "marriage-good-method-1", label: "Method 1", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "if-a-marriage-is-good-or-not" }, { id: "marriage-good-method-2", label: "Method 2", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "if-a-marriage-is-good-or-not" }],
  },
  "if-the-prayers-done-for-someone-have-been": {
    id: "if-the-prayers-done-for-someone-have-been",
    title: "Have the prayers done for this person been answered?",
    categoryId: "fate-timing",
    chapterId: "if-the-prayers-done-for-someone-have-been",
    resultKind: null,
    methods: [{ id: "prayers-answered-method-1", label: "Method 1", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "if-the-prayers-done-for-someone-have-been" }],
  },
  "if-the-lady-or-man-you-are-going": {
    id: "if-the-lady-or-man-you-are-going",
    title: "Are they related to me by family?",
    categoryId: "love-couple",
    chapterId: "if-the-lady-or-man-you-are-going",
    resultKind: "descriptive",
    methods: [{ id: "related-by-family-method-1", label: "Method 1", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "if-the-lady-or-man-you-are-going" }],
  },
  "if-a-marriage-will-last-forever": {
    id: "if-a-marriage-will-last-forever",
    title: "Will this marriage last forever?",
    categoryId: "love-couple",
    chapterId: "if-a-marriage-will-last-forever",
    resultKind: null,
    methods: [{ id: "marriage-last-forever-method-1", label: "Method 1", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "if-a-marriage-will-last-forever" }, { id: "marriage-last-forever-method-2", label: "Method 2", status: "uncertain", sourceBook: "kanzul-mikban", sourceChapterId: "if-a-marriage-will-last-forever" }],
  },
  "if-a-partner-has-a-particular-disease-or": {
    id: "if-a-partner-has-a-particular-disease-or",
    title: "Does my partner have a particular disease or sickness?",
    categoryId: "health-hardships",
    chapterId: "if-a-partner-has-a-particular-disease-or",
    resultKind: null,
    methods: [{ id: "partner-disease-method-1", label: "Method 1", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "if-a-partner-has-a-particular-disease-or" }, { id: "partner-disease-method-2", label: "Method 2", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "if-a-partner-has-a-particular-disease-or" }, { id: "partner-disease-method-3", label: "Method 3", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "if-a-partner-has-a-particular-disease-or" }],
  },
  "if-someone-has-married-before-or-if-he": {
    id: "if-someone-has-married-before-or-if-he",
    title: "Has this person married before, or are they married now?",
    categoryId: "love-couple",
    chapterId: "if-someone-has-married-before-or-if-he",
    resultKind: "descriptive",
    methods: [{ id: "married-before-method-1", label: "Method 1", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "if-someone-has-married-before-or-if-he" }],
  },
  "if-she-he-is-still-in-the-marriage": {
    id: "if-she-he-is-still-in-the-marriage",
    title: "Are they still in this marriage?",
    categoryId: "love-couple",
    chapterId: "if-she-he-is-still-in-the-marriage",
    resultKind: "descriptive",
    methods: [{ id: "still-in-marriage-method-1", label: "Method 1", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "if-she-he-is-still-in-the-marriage" }],
  },
  "if-he-she-is-enjoying-the-marriage": {
    id: "if-he-she-is-enjoying-the-marriage",
    title: "Is he/she enjoying the marriage?",
    categoryId: "love-couple",
    chapterId: "if-he-she-is-enjoying-the-marriage",
    resultKind: null,
    methods: [{ id: "enjoying-marriage-method-1", label: "Method 1", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "if-he-she-is-enjoying-the-marriage" }],
  },
  "if-your-partner-is-cheating-on-you": {
    id: "if-your-partner-is-cheating-on-you",
    title: "Is my partner cheating on me?",
    categoryId: "love-couple",
    chapterId: "if-your-partner-is-cheating-on-you",
    resultKind: null,
    methods: [{ id: "partner-cheating-method-1", label: "Method 1", status: "needs_review", sourceBook: "kanzul-mikban", sourceChapterId: "if-your-partner-is-cheating-on-you" }],
  },
  "if-your-ex-husband-wife-will-re-marry": {
    id: "if-your-ex-husband-wife-will-re-marry",
    title: "Will my ex re-marry after the divorce?",
    categoryId: "love-couple",
    chapterId: "if-your-ex-husband-wife-will-re-marry",
    resultKind: null,
    methods: [{ id: "ex-remarry-method-1", label: "Method 1", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "if-your-ex-husband-wife-will-re-marry" }],
  },
  "if-a-pregnant-woman-will-have-childbirth-problems": {
    id: "if-a-pregnant-woman-will-have-childbirth-problems",
    title: "Will she have childbirth problems in her marriage?",
    categoryId: "love-couple",
    chapterId: "if-a-pregnant-woman-will-have-childbirth-problems",
    resultKind: null,
    methods: [{ id: "childbirth-problems-method-1", label: "Method 1", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "if-a-pregnant-woman-will-have-childbirth-problems" }, { id: "childbirth-problems-method-2", label: "Method 2", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "if-a-pregnant-woman-will-have-childbirth-problems" }],
  },
  "if-a-man-will-have-manhood-problems-in": {
    id: "if-a-man-will-have-manhood-problems-in",
    title: "Will he have manhood problems in his marriage or life?",
    categoryId: "love-couple",
    chapterId: "if-a-man-will-have-manhood-problems-in",
    resultKind: null,
    methods: [{ id: "manhood-problems-method-1", label: "Method 1", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "if-a-man-will-have-manhood-problems-in" }, { id: "manhood-problems-method-2", label: "Method 2", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "if-a-man-will-have-manhood-problems-in" }],
  },
  "if-a-lady-or-man-has-feelings-for": {
    id: "if-a-lady-or-man-has-feelings-for",
    title: "Do they have feelings for me?",
    categoryId: "love-couple",
    chapterId: "if-a-lady-or-man-has-feelings-for",
    resultKind: null,
    methods: [{ id: "feelings-for-you-method-1", label: "Method 1", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "if-a-lady-or-man-has-feelings-for" }],
  },
  "if-a-woman-has-married-more-than-one": {
    id: "if-a-woman-has-married-more-than-one",
    title: "How many men has she married at the same time?",
    categoryId: "love-couple",
    chapterId: "if-a-woman-has-married-more-than-one",
    resultKind: "descriptive",
    methods: [{ id: "polyandry-method-1", label: "Method 1", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "if-a-woman-has-married-more-than-one" }],
  },
  "if-someone-is-an-adulterous-son-daughter-born": {
    id: "if-someone-is-an-adulterous-son-daughter-born",
    title: "Was this person born out of wedlock?",
    categoryId: "love-couple",
    chapterId: "if-someone-is-an-adulterous-son-daughter-born",
    resultKind: null,
    methods: [{ id: "born-out-of-wedlock-method-1", label: "Method 1", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "if-someone-is-an-adulterous-son-daughter-born" }],
  },
  "if-he-she-is-a-womanizer-or-a": {
    id: "if-he-she-is-a-womanizer-or-a",
    title: "Is he/she a womanizer or a harlot?",
    categoryId: "love-couple",
    chapterId: "if-he-she-is-a-womanizer-or-a",
    resultKind: null,
    methods: [{ id: "womanizer-method-1", label: "Method 1", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "if-he-she-is-a-womanizer-or-a" }],
  },
  "if-your-ex-husband-wife-girlfriend-or-boyfriend": {
    id: "if-your-ex-husband-wife-girlfriend-or-boyfriend",
    title: "Will my ex come back to me?",
    categoryId: "love-couple",
    chapterId: "if-your-ex-husband-wife-girlfriend-or-boyfriend",
    resultKind: null,
    methods: [{ id: "ex-return-method-1", label: "Method 1", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "if-your-ex-husband-wife-girlfriend-or-boyfriend" }, { id: "ex-return-method-2", label: "Method 2", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "if-your-ex-husband-wife-girlfriend-or-boyfriend" }],
  },
  "if-the-pregnancy-is-healthy-or-not": {
    id: "if-the-pregnancy-is-healthy-or-not",
    title: "Is the pregnancy healthy?",
    categoryId: "family-loved-ones",
    chapterId: "if-the-pregnancy-is-healthy-or-not",
    resultKind: null,
    methods: [{ id: "pregnancy-healthy-method-1", label: "Method 1", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "if-the-pregnancy-is-healthy-or-not" }, { id: "pregnancy-healthy-method-2", label: "Method 2", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "if-the-pregnancy-is-healthy-or-not" }],
  },
  "the-number-of-months-of-a-pregnancy-how": {
    id: "the-number-of-months-of-a-pregnancy-how",
    title: "How many months old is this pregnancy?",
    categoryId: "family-loved-ones",
    chapterId: "the-number-of-months-of-a-pregnancy-how",
    resultKind: "descriptive",
    methods: [{ id: "pregnancy-months-method-1", label: "Method 1", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "the-number-of-months-of-a-pregnancy-how" }],
  },
  "the-number-of-babies-in-a-pregnancy": {
    id: "the-number-of-babies-in-a-pregnancy",
    title: "How many babies are in this pregnancy?",
    categoryId: "family-loved-ones",
    chapterId: "the-number-of-babies-in-a-pregnancy",
    resultKind: "descriptive",
    methods: [{ id: "number-of-babies-method-1", label: "Method 1", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "the-number-of-babies-in-a-pregnancy" }, { id: "number-of-babies-method-2", label: "Method 2", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "the-number-of-babies-in-a-pregnancy" }],
  },
  "if-a-pregnancy-is-yours-or-not-d": {
    id: "if-a-pregnancy-is-yours-or-not-d",
    title: "Is this pregnancy mine?",
    categoryId: "family-loved-ones",
    chapterId: "if-a-pregnancy-is-yours-or-not-d",
    resultKind: "descriptive",
    methods: [{ id: "pregnancy-paternity-method-1", label: "Method 1", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "if-a-pregnancy-is-yours-or-not-d" }, { id: "pregnancy-paternity-method-2", label: "Method 2", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "if-a-pregnancy-is-yours-or-not-d" }],
  },
  "if-she-will-put-to-bed-peacefully-or": {
    id: "if-she-will-put-to-bed-peacefully-or",
    title: "Will she put to bed peacefully?",
    categoryId: "family-loved-ones",
    chapterId: "if-she-will-put-to-bed-peacefully-or",
    resultKind: null,
    methods: [{ id: "put-to-bed-peacefully-method-1", label: "Method 1", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "if-she-will-put-to-bed-peacefully-or" }],
  },
  "the-time-she-will-put-to-bed": {
    id: "the-time-she-will-put-to-bed",
    title: "How soon will she put to bed?",
    categoryId: "family-loved-ones",
    chapterId: "the-time-she-will-put-to-bed",
    resultKind: "descriptive",
    methods: [{ id: "time-to-put-to-bed-method-1", label: "Method 1", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "the-time-she-will-put-to-bed" }, { id: "time-to-put-to-bed-method-2", label: "Method 2", status: "uncertain", sourceBook: "kanzul-mikban", sourceChapterId: "the-time-she-will-put-to-bed" }],
  },
  "if-it-s-day-or-night-that-she": {
    id: "if-it-s-day-or-night-that-she",
    title: "Will she put to bed in the daytime or at night?",
    categoryId: "family-loved-ones",
    chapterId: "if-it-s-day-or-night-that-she",
    resultKind: "descriptive",
    methods: [{ id: "day-or-night-birth-method-1", label: "Method 1", status: "needs_review", sourceBook: "kanzul-mikban", sourceChapterId: "if-it-s-day-or-night-that-she" }],
  },
  "if-your-enemy-is-from-your-father-s": {
    id: "if-your-enemy-is-from-your-father-s",
    title: "Is my enemy from my family, or someone close to me?",
    categoryId: "love-couple",
    chapterId: "if-your-enemy-is-from-your-father-s",
    resultKind: "descriptive",
    methods: [{ id: "enemy-family-origin-method-1", label: "Method 1", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "if-your-enemy-is-from-your-father-s" }, { id: "enemy-family-origin-method-2", label: "Method 2", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "if-your-enemy-is-from-your-father-s" }, { id: "enemy-family-origin-method-3", label: "Method 3", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "if-your-enemy-is-from-your-father-s" }],
  },
  "how-the-future-of-two-people-s-friendship": {
    id: "how-the-future-of-two-people-s-friendship",
    title: "How will our friendship turn out?",
    categoryId: "family-loved-ones",
    chapterId: "how-the-future-of-two-people-s-friendship",
    resultKind: null,
    methods: [{ id: "friendship-future-method-1", label: "Method 1 (direction)", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "how-the-future-of-two-people-s-friendship" }, { id: "friendship-future-method-2", label: "Method 2 (stability)", status: "needs_review", sourceBook: "kanzul-mikban", sourceChapterId: "how-the-future-of-two-people-s-friendship" }],
  },
  "secrets-between-two-friends-who-follow-each-other": {
    id: "secrets-between-two-friends-who-follow-each-other",
    title: "Will our secrets stay between us?",
    categoryId: "family-loved-ones",
    chapterId: "secrets-between-two-friends-who-follow-each-other",
    resultKind: "descriptive",
    methods: [{ id: "friendship-secrets-method-1", label: "Method 1", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "secrets-between-two-friends-who-follow-each-other" }],
  },
  "if-it-s-business-or-handwork-that-will": {
    id: "if-it-s-business-or-handwork-that-will",
    title: "Is business or handwork better for me?",
    categoryId: "work-success",
    chapterId: "if-it-s-business-or-handwork-that-will",
    resultKind: "descriptive",
    methods: [{ id: "business-or-handwork-method-1", label: "Method 1 (direction)", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "if-it-s-business-or-handwork-that-will" }, { id: "business-or-handwork-method-2", label: "Method 2 (stability)", status: "needs_review", sourceBook: "kanzul-mikban", sourceChapterId: "if-it-s-business-or-handwork-that-will" }],
  },
  "when-your-suffering-and-pain-or-sadness-will": {
    id: "when-your-suffering-and-pain-or-sadness-will",
    title: "When will my suffering end?",
    categoryId: "health-hardships",
    chapterId: "when-your-suffering-and-pain-or-sadness-will",
    resultKind: null,
    methods: [{ id: "suffering-will-end-method-1", label: "Method 1", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "when-your-suffering-and-pain-or-sadness-will" }],
  },
  "if-you-will-get-a-position-rank-or": {
    id: "if-you-will-get-a-position-rank-or",
    title: "Will I get this position or rank?",
    categoryId: "work-success",
    chapterId: "if-you-will-get-a-position-rank-or",
    resultKind: null,
    methods: [{ id: "position-or-rank-method-1", label: "Method 1", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "if-you-will-get-a-position-rank-or" }],
  },
  "if-your-success-or-wealth-will-remain-forever": {
    id: "if-your-success-or-wealth-will-remain-forever",
    title: "Will my success or wealth remain forever?",
    categoryId: "money-possessions",
    chapterId: "if-your-success-or-wealth-will-remain-forever",
    resultKind: null,
    methods: [{ id: "wealth-permanence-method-1", label: "Method 1", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "if-your-success-or-wealth-will-remain-forever" }],
  },
  "if-someone-s-misery-will-be-taken-away": {
    id: "if-someone-s-misery-will-be-taken-away",
    title: "Will my misery be taken away?",
    categoryId: "health-hardships",
    chapterId: "if-someone-s-misery-will-be-taken-away",
    resultKind: null,
    methods: [{ id: "misery-taken-away-method-1", label: "Method 1", status: "uncertain", sourceBook: "kanzul-mikban", sourceChapterId: "if-someone-s-misery-will-be-taken-away" }, { id: "misery-taken-away-method-2", label: "Method 2", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "if-someone-s-misery-will-be-taken-away" }],
  },
  "if-something-is-present-past-or-future": {
    id: "if-something-is-present-past-or-future",
    title: "Is this about the present, the past, or the future?",
    categoryId: "fate-timing",
    chapterId: "if-something-is-present-past-or-future",
    resultKind: "descriptive",
    methods: [{ id: "present-past-future-method-1", label: "Method 1", status: "needs_review", sourceBook: "kanzul-mikban", sourceChapterId: "if-something-is-present-past-or-future" }],
  },
  "the-ending-part-of-anything-you-want-to": {
    id: "the-ending-part-of-anything-you-want-to",
    title: "How will this end up?",
    categoryId: "fate-timing",
    chapterId: "the-ending-part-of-anything-you-want-to",
    resultKind: null,
    methods: [{ id: "ending-of-anything-method-1", label: "Method 1", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "the-ending-part-of-anything-you-want-to" }],
  },
  "if-someone-has-long-life-or-not": {
    id: "if-someone-has-long-life-or-not",
    title: "Will they have a long life?",
    categoryId: "health-hardships",
    chapterId: "if-someone-has-long-life-or-not",
    resultKind: null,
    methods: [{ id: "long-life-method-1", label: "Method 1", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "if-someone-has-long-life-or-not" }],
  },
  "the-lifespan-and-when-someone-will-die": {
    id: "the-lifespan-and-when-someone-will-die",
    title: "What is their lifespan?",
    categoryId: "health-hardships",
    chapterId: "the-lifespan-and-when-someone-will-die",
    resultKind: "descriptive",
    methods: [{ id: "lifespan-when-death-method-1", label: "Method 1", status: "uncertain", sourceBook: "kanzul-mikban", sourceChapterId: "the-lifespan-and-when-someone-will-die" }],
  },
  "if-a-sick-person-has-long-life-or": {
    id: "if-a-sick-person-has-long-life-or",
    title: "Does this sick person have long life?",
    categoryId: "health-hardships",
    chapterId: "if-a-sick-person-has-long-life-or",
    resultKind: null,
    methods: [{ id: "sick-person-long-life-method-1", label: "Method 1", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "if-a-sick-person-has-long-life-or" }, { id: "sick-person-long-life-method-2", label: "Method 2", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "if-a-sick-person-has-long-life-repeated" }],
  },
  "where-one-will-die-place-of-death": {
    id: "where-one-will-die-place-of-death",
    title: "Where will they die?",
    categoryId: "health-hardships",
    chapterId: "where-one-will-die-place-of-death",
    resultKind: "descriptive",
    methods: [{ id: "place-of-death-method-1", label: "Method 1", status: "uncertain", sourceBook: "kanzul-mikban", sourceChapterId: "where-one-will-die-place-of-death" }],
  },
  "the-causes-of-someone-s-death": {
    id: "the-causes-of-someone-s-death",
    title: "What will the cause of death be?",
    categoryId: "health-hardships",
    chapterId: "the-causes-of-someone-s-death",
    resultKind: "descriptive",
    methods: [{ id: "causes-of-death-method-1", label: "Method 1", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "the-causes-of-someone-s-death" }],
  },
  "if-someone-or-something-good-will-come-to": {
    id: "if-someone-or-something-good-will-come-to",
    title: "Will something good come to me today?",
    categoryId: "fate-timing",
    chapterId: "if-someone-or-something-good-will-come-to",
    resultKind: null,
    methods: [{ id: "something-good-today-method-1", label: "Method 1", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "if-someone-or-something-good-will-come-to" }],
  },
  "if-today-is-a-good-day-or-not": {
    id: "if-today-is-a-good-day-or-not",
    title: "Is today a good day?",
    categoryId: "fate-timing",
    chapterId: "if-today-is-a-good-day-or-not",
    resultKind: null,
    methods: [{ id: "today-good-day-method-1", label: "Method 1", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "if-today-is-a-good-day-or-not" }],
  },
  "as-a-stranger-if-the-food-you-want": {
    id: "as-a-stranger-if-the-food-you-want",
    title: "Is this food home-prepared or from the market?",
    categoryId: "fate-timing",
    chapterId: "as-a-stranger-if-the-food-you-want",
    resultKind: "descriptive",
    methods: [{ id: "food-market-or-home-method-1", label: "Method 1", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "as-a-stranger-if-the-food-you-want" }],
  },
  "if-this-money-the-work-or-the-lady": {
    id: "if-this-money-the-work-or-the-lady",
    title: "Will this money, work, or relationship be stable?",
    categoryId: "money-possessions",
    chapterId: "if-this-money-the-work-or-the-lady",
    resultKind: "descriptive",
    methods: [{ id: "money-work-lady-stable-method-1", label: "Method 1", status: "uncertain", sourceBook: "kanzul-mikban", sourceChapterId: "if-this-money-the-work-or-the-lady" }],
  },
  "if-the-querent-is-sick-or-not": {
    id: "if-the-querent-is-sick-or-not",
    title: "Am I sick right now?",
    categoryId: "health-hardships",
    chapterId: "if-the-querent-is-sick-or-not",
    resultKind: null,
    methods: [{ id: "querent-sick-method-1", label: "Method 1", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "if-the-querent-is-sick-or-not" }, { id: "querent-sick-method-2", label: "Method 2", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "if-the-querent-is-sick-or-not" }],
  },
  "if-the-sickness-is-from-human-jinn-or": {
    id: "if-the-sickness-is-from-human-jinn-or",
    title: "Where does this sickness come from?",
    categoryId: "health-hardships",
    chapterId: "if-the-sickness-is-from-human-jinn-or",
    resultKind: "descriptive",
    methods: [{ id: "sickness-cause-method-1", label: "Method 1", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "if-the-sickness-is-from-human-jinn-or" }],
  },
  "which-part-of-the-body-is-paining-the": {
    id: "which-part-of-the-body-is-paining-the",
    title: "Which part of the body is in pain?",
    categoryId: "health-hardships",
    chapterId: "which-part-of-the-body-is-paining-the",
    resultKind: "descriptive",
    methods: [{ id: "body-part-in-pain-method-1", label: "Method 1", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "which-part-of-the-body-is-paining-the" }],
  },
  "if-you-will-see-what-you-are-searching": {
    id: "if-you-will-see-what-you-are-searching",
    title: "Will I see what I am searching for?",
    categoryId: "lost-stolen",
    chapterId: "if-you-will-see-what-you-are-searching",
    resultKind: "descriptive",
    methods: [{ id: "see-what-searching-for-method-1", label: "Method 1", status: "uncertain", sourceBook: "kanzul-mikban", sourceChapterId: "if-you-will-see-what-you-are-searching" }],
  },
  "if-you-will-get-to-talk-to-someone": {
    id: "if-you-will-get-to-talk-to-someone",
    title: "Will we get to talk?",
    categoryId: "fate-timing",
    chapterId: "if-you-will-get-to-talk-to-someone",
    resultKind: "descriptive",
    methods: [{ id: "conversation-will-happen-method-1", label: "Method 1", status: "uncertain", sourceBook: "kanzul-mikban", sourceChapterId: "if-you-will-get-to-talk-to-someone" }],
  },
  "if-you-will-get-what-you-are-searching": {
    id: "if-you-will-get-what-you-are-searching",
    title: "Will I get what I am searching for, in this place?",
    categoryId: "lost-stolen",
    chapterId: "if-you-will-get-what-you-are-searching",
    resultKind: "descriptive",
    methods: [{ id: "get-what-searching-for-in-place-method-1", label: "Method 1", status: "uncertain", sourceBook: "kanzul-mikban", sourceChapterId: "if-you-will-get-what-you-are-searching" }],
  },
  "if-you-won-t-get-what-you-are": {
    id: "if-you-won-t-get-what-you-are",
    title: "What will block me from getting what I want?",
    categoryId: "lost-stolen",
    chapterId: "if-you-won-t-get-what-you-are",
    resultKind: "descriptive",
    methods: [{ id: "what-blocks-you-method-1", label: "Method 1", status: "uncertain", sourceBook: "kanzul-mikban", sourceChapterId: "if-you-won-t-get-what-you-are" }],
  },
  "if-you-have-enemies-and-how-many": {
    id: "if-you-have-enemies-and-how-many",
    title: "Do I have enemies, and how many?",
    categoryId: "legal-conflict",
    chapterId: "if-you-have-enemies-and-how-many",
    resultKind: "descriptive",
    methods: [{ id: "enemies-how-many-method-1", label: "Method 1", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "if-you-have-enemies-and-how-many" }, { id: "enemies-how-many-method-2", label: "Method 2", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "if-you-have-enemies-and-how-many" }],
  },
  "if-you-will-get-knowledge-or-not-in": {
    id: "if-you-will-get-knowledge-or-not-in",
    title: "Will I gain knowledge and wisdom in my life?",
    categoryId: "fate-timing",
    chapterId: "if-you-will-get-knowledge-or-not-in",
    resultKind: null,
    methods: [{ id: "get-knowledge-in-life-method-1", label: "Method 1", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "if-you-will-get-knowledge-or-not-in" }],
  },
  "if-you-will-get-what-you-want-or": {
    id: "if-you-will-get-what-you-want-or",
    title: "Will I get what I want, and how soon?",
    categoryId: "fate-timing",
    chapterId: "if-you-will-get-what-you-want-or",
    resultKind: null,
    methods: [{ id: "get-what-you-want-very-close-method-1-direction", label: "Method 1 (direction)", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "if-you-will-get-what-you-want-or" }, { id: "get-what-you-want-very-close-method-1-stability", label: "Method 1 (stability)", status: "needs_review", sourceBook: "kanzul-mikban", sourceChapterId: "if-you-will-get-what-you-want-or" }, { id: "get-what-you-want-very-close-method-2-direction", label: "Method 2 (direction)", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "if-you-will-get-what-you-want-or" }, { id: "get-what-you-want-very-close-method-2-stability", label: "Method 2 (stability)", status: "needs_review", sourceBook: "kanzul-mikban", sourceChapterId: "if-you-will-get-what-you-want-or" }],
  },
  "if-something-will-burn": {
    id: "if-something-will-burn",
    title: "Will something burn?",
    categoryId: "fate-timing",
    chapterId: "if-something-will-burn",
    resultKind: null,
    methods: [{ id: "something-will-burn-method-1", label: "Method 1", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "if-something-will-burn" }],
  },
  "if-something-has-really-been-stolen-or-not": {
    id: "if-something-has-really-been-stolen-or-not",
    title: "Has this really been stolen?",
    categoryId: "lost-stolen",
    chapterId: "if-something-has-really-been-stolen-or-not",
    resultKind: "descriptive",
    methods: [{ id: "something-really-stolen-method-1", label: "Method 1", status: "uncertain", sourceBook: "kanzul-mikban", sourceChapterId: "if-something-has-really-been-stolen-or-not" }, { id: "something-really-stolen-method-2", label: "Method 2", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "if-something-has-really-been-stolen-or-not" }],
  },
  "if-they-will-return-a-stolen-thing-back": {
    id: "if-they-will-return-a-stolen-thing-back",
    title: "Will the stolen thing be returned?",
    categoryId: "lost-stolen",
    chapterId: "if-they-will-return-a-stolen-thing-back",
    resultKind: null,
    methods: [{ id: "stolen-thing-returned-method-1", label: "Method 1", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "if-they-will-return-a-stolen-thing-back" }],
  },
  "the-number-of-thieves": {
    id: "the-number-of-thieves",
    title: "How many thieves are there?",
    categoryId: "legal-conflict",
    chapterId: "the-number-of-thieves",
    resultKind: "descriptive",
    methods: [{ id: "number-of-thieves-method-1", label: "Method 1", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "the-number-of-thieves" }],
  },
  "the-description-of-the-thief": {
    id: "the-description-of-the-thief",
    title: "What does the thief look like?",
    categoryId: "legal-conflict",
    chapterId: "the-description-of-the-thief",
    resultKind: "descriptive",
    methods: [{ id: "thief-description-method-1", label: "Method 1 (H1)", status: "needs_review", sourceBook: "kanzul-mikban", sourceChapterId: "the-description-of-the-thief" }, { id: "thief-description-method-2", label: "Method 2 (H7 alternate)", status: "needs_review", sourceBook: "kanzul-mikban", sourceChapterId: "the-description-of-the-thief" }],
  },
  "if-the-thief-or-the-stolen-thing-is": {
    id: "if-the-thief-or-the-stolen-thing-is",
    title: "Is the thief (or the stolen thing) still in town?",
    categoryId: "legal-conflict",
    chapterId: "if-the-thief-or-the-stolen-thing-is",
    resultKind: "descriptive",
    methods: [{ id: "thief-in-town-or-out-method-1", label: "Method 1", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "if-the-thief-or-the-stolen-thing-is" }],
  },
  "if-it-is-the-accused-person-that-stole": {
    id: "if-it-is-the-accused-person-that-stole",
    title: "Is the accused person the one who stole it?",
    categoryId: "legal-conflict",
    chapterId: "if-it-is-the-accused-person-that-stole",
    resultKind: "descriptive",
    methods: [{ id: "accused-person-guilty-method-1-direction", label: "Method 1 (direction)", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "if-it-is-the-accused-person-that-stole" }, { id: "accused-person-guilty-method-1-stability", label: "Method 1 (stability)", status: "needs_review", sourceBook: "kanzul-mikban", sourceChapterId: "if-it-is-the-accused-person-that-stole" }],
  },
  "the-thief-from-among-the-accused-people": {
    id: "the-thief-from-among-the-accused-people",
    title: "Which of the accused people is the thief?",
    categoryId: "legal-conflict",
    chapterId: "the-thief-from-among-the-accused-people",
    resultKind: "descriptive",
    methods: [{ id: "thief-among-accused-method-1-direction", label: "Method 1 (direction)", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "the-thief-from-among-the-accused-people" }, { id: "thief-among-accused-method-1-stability", label: "Method 1 (stability)", status: "needs_review", sourceBook: "kanzul-mikban", sourceChapterId: "the-thief-from-among-the-accused-people" }, { id: "thief-among-accused-method-2", label: "Method 2 (directional)", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "the-thief-from-among-the-accused-people" }],
  },
  "if-something-was-buried-or-has-been-buried": {
    id: "if-something-was-buried-or-has-been-buried",
    title: "Was something buried in this place?",
    categoryId: "lost-stolen",
    chapterId: "if-something-was-buried-or-has-been-buried",
    resultKind: "descriptive",
    methods: [{ id: "something-buried-method-1", label: "Method 1", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "if-something-was-buried-or-has-been-buried" }, { id: "something-buried-method-2", label: "Method 2", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "if-something-was-buried-or-has-been-buried" }, { id: "something-buried-method-3", label: "Method 3", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "if-something-was-buried-or-has-been-buried" }],
  },
  "if-there-s-a-hidden-treasure-gold-money": {
    id: "if-there-s-a-hidden-treasure-gold-money",
    title: "Is there hidden treasure in this place?",
    categoryId: "lost-stolen",
    chapterId: "if-there-s-a-hidden-treasure-gold-money",
    resultKind: "descriptive",
    methods: [{ id: "hidden-treasure-method-1", label: "Method 1", status: "uncertain", sourceBook: "kanzul-mikban", sourceChapterId: "if-there-s-a-hidden-treasure-gold-money" }, { id: "hidden-treasure-method-2", label: "Method 2", status: "uncertain", sourceBook: "kanzul-mikban", sourceChapterId: "if-there-s-a-hidden-treasure-gold-money" }, { id: "hidden-treasure-method-3-direction", label: "Method 3 (direction)", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "if-there-s-a-hidden-treasure-gold-money" }, { id: "hidden-treasure-method-3-stability", label: "Method 3 (stability)", status: "needs_review", sourceBook: "kanzul-mikban", sourceChapterId: "if-there-s-a-hidden-treasure-gold-money" }],
  },
  "how-deep-something-is-buried": {
    id: "how-deep-something-is-buried",
    title: "How deep is it buried?",
    categoryId: "lost-stolen",
    chapterId: "how-deep-something-is-buried",
    resultKind: "descriptive",
    methods: [{ id: "how-deep-buried-method-1", label: "Method 1", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "how-deep-something-is-buried" }],
  },
  "where-a-traveller-has-travelled-to": {
    id: "where-a-traveller-has-travelled-to",
    title: "Where has the traveller gone?",
    categoryId: "travel-change",
    chapterId: "where-a-traveller-has-travelled-to",
    resultKind: "descriptive",
    methods: [{ id: "traveller-destination-method-1", label: "Method 1", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "where-a-traveller-has-travelled-to" }],
  },
  "if-the-traveller-has-travelled-by-air-water": {
    id: "if-the-traveller-has-travelled-by-air-water",
    title: "Did the traveller go by air, water, or land?",
    categoryId: "travel-change",
    chapterId: "if-the-traveller-has-travelled-by-air-water",
    resultKind: "descriptive",
    methods: [{ id: "traveller-mode-method-1", label: "Method 1", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "if-the-traveller-has-travelled-by-air-water" }],
  },
  "if-the-traveller-has-reached-where-he-she": {
    id: "if-the-traveller-has-reached-where-he-she",
    title: "Has the traveller reached their destination?",
    categoryId: "travel-change",
    chapterId: "if-the-traveller-has-reached-where-he-she",
    resultKind: "descriptive",
    methods: [{ id: "traveller-reached-destination-method-1", label: "Method 1", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "if-the-traveller-has-reached-where-he-she" }],
  },
  "if-someone-is-truthful-or-not": {
    id: "if-someone-is-truthful-or-not",
    title: "Is this person telling the truth?",
    categoryId: "legal-conflict",
    chapterId: "if-someone-is-truthful-or-not",
    resultKind: "descriptive",
    methods: [{ id: "truthful-or-not-method-1", label: "Method 1", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "if-someone-is-truthful-or-not" }, { id: "truthful-or-not-method-2", label: "Method 2", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "if-someone-is-truthful-or-not" }],
  },
  "if-a-prisoner-will-come-out-of-prison": {
    id: "if-a-prisoner-will-come-out-of-prison",
    title: "Will the prisoner come out, and how long will it take?",
    categoryId: "legal-conflict",
    chapterId: "if-a-prisoner-will-come-out-of-prison",
    resultKind: null,
    methods: [{ id: "prisoner-come-out-method-1", label: "Method 1", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "if-a-prisoner-will-come-out-of-prison" }, { id: "prisoner-come-out-method-2", label: "Method 2", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "if-a-prisoner-will-come-out-of-prison" }],
  },
  "if-the-prisoner-will-be-removed-peacefully": {
    id: "if-the-prisoner-will-be-removed-peacefully",
    title: "Will the prisoner be removed peacefully?",
    categoryId: "legal-conflict",
    chapterId: "if-the-prisoner-will-be-removed-peacefully",
    resultKind: null,
    methods: [{ id: "prisoner-removed-peacefully-method-1", label: "Method 1", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "if-the-prisoner-will-be-removed-peacefully" }],
  },
  "how-long-the-prisoner-will-stay-in-prison": {
    id: "how-long-the-prisoner-will-stay-in-prison",
    title: "How long will the prisoner stay in prison?",
    categoryId: "legal-conflict",
    chapterId: "how-long-the-prisoner-will-stay-in-prison",
    resultKind: null,
    methods: [{ id: "how-long-prisoner-stay-method-1", label: "Method 1", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "how-long-the-prisoner-will-stay-in-prison" }],
  },
  "if-the-prisoner-is-male-or-female": {
    id: "if-the-prisoner-is-male-or-female",
    title: "Is the prisoner male or female?",
    categoryId: "legal-conflict",
    chapterId: "if-the-prisoner-is-male-or-female",
    resultKind: "descriptive",
    methods: [{ id: "prisoner-male-or-female-method-1", label: "Method 1", status: "needs_review", sourceBook: "kanzul-mikban", sourceChapterId: "if-the-prisoner-is-male-or-female" }],
  },
  "where-kidnappers-are-keeping-a-person-hostage": {
    id: "where-kidnappers-are-keeping-a-person-hostage",
    title: "Where are the kidnappers keeping the person?",
    categoryId: "legal-conflict",
    chapterId: "where-kidnappers-are-keeping-a-person-hostage",
    resultKind: "descriptive",
    methods: [{ id: "kidnapper-location-method-1", label: "Method 1", status: "uncertain", sourceBook: "kanzul-mikban", sourceChapterId: "where-kidnappers-are-keeping-a-person-hostage" }],
  },
  "the-consequence-of-a-prisoner": {
    id: "the-consequence-of-a-prisoner",
    title: "What will happen to the prisoner afterward?",
    categoryId: "legal-conflict",
    chapterId: "the-consequence-of-a-prisoner",
    resultKind: null,
    methods: [{ id: "prisoner-consequence-method-1", label: "Method 1", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "the-consequence-of-a-prisoner" }, { id: "prisoner-consequence-method-2", label: "Method 2", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "the-consequence-of-a-prisoner" }],
  },
  "if-you-will-get-your-debts-deposit-or": {
    id: "if-you-will-get-your-debts-deposit-or",
    title: "Will I get my debts, deposit, or savings back?",
    categoryId: "money-possessions",
    chapterId: "if-you-will-get-your-debts-deposit-or",
    resultKind: null,
    methods: [{ id: "debts-deposit-back-method-1", label: "Method 1", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "if-you-will-get-your-debts-deposit-or" }],
  },
  "if-someone-will-get-a-particular-position-or": {
    id: "if-someone-will-get-a-particular-position-or",
    title: "Will I get a particular position or chieftaincy title?",
    categoryId: "work-success",
    chapterId: "if-someone-will-get-a-particular-position-or",
    resultKind: null,
    methods: [{ id: "get-position-or-chieftaincy-method-1", label: "Method 1", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "if-someone-will-get-a-particular-position-or" }],
  },
  "if-you-will-own-a-house-in-your": {
    id: "if-you-will-own-a-house-in-your",
    title: "Will I own a house in my life?",
    categoryId: "work-success",
    chapterId: "if-you-will-own-a-house-in-your",
    resultKind: null,
    methods: [{ id: "own-house-in-life-method-1", label: "Method 1", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "if-you-will-own-a-house-in-your" }],
  },
  "if-this-apartment-you-are-going-to-is": {
    id: "if-this-apartment-you-are-going-to-is",
    title: "Is this apartment safe/good for me?",
    categoryId: "work-success",
    chapterId: "if-this-apartment-you-are-going-to-is",
    resultKind: null,
    methods: [{ id: "apartment-safe-for-you-method-1", label: "Method 1", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "if-this-apartment-you-are-going-to-is" }],
  },
  "if-you-will-receive-the-expected-message": {
    id: "if-you-will-receive-the-expected-message",
    title: "Will I receive the expected message?",
    categoryId: "fate-timing",
    chapterId: "if-you-will-receive-the-expected-message",
    resultKind: null,
    methods: [{ id: "receive-expected-message-method-1", label: "Method 1", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "if-you-will-receive-the-expected-message" }],
  },
  "which-day-a-pregnant-woman-will-put-to": {
    id: "which-day-a-pregnant-woman-will-put-to",
    title: "Which day will the pregnant woman put to bed?",
    categoryId: "family-loved-ones",
    chapterId: "which-day-a-pregnant-woman-will-put-to",
    resultKind: "descriptive",
    methods: [{ id: "pregnant-woman-put-to-bed-day-method-1", label: "Method 1", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "which-day-a-pregnant-woman-will-put-to" }],
  },
  "if-you-will-get-back-to-work-after": {
    id: "if-you-will-get-back-to-work-after",
    title: "Will I get back to work after this workplace problem?",
    categoryId: "work-success",
    chapterId: "if-you-will-get-back-to-work-after",
    resultKind: null,
    methods: [{ id: "back-to-work-after-problem-method-1", label: "Method 1", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "if-you-will-get-back-to-work-after" }],
  },
  "if-she-s-going-to-stay-in-the": {
    id: "if-she-s-going-to-stay-in-the",
    title: "Will she stay in the marriage?",
    categoryId: "love-couple",
    chapterId: "if-she-s-going-to-stay-in-the",
    resultKind: null,
    methods: [{ id: "stay-in-marriage-method-1", label: "Method 1", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "if-she-s-going-to-stay-in-the" }, { id: "stay-in-marriage-method-2", label: "Method 2", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "if-she-s-going-to-stay-in-the" }],
  },
  "the-consequence-of-friendship-between-two-people": {
    id: "the-consequence-of-friendship-between-two-people",
    title: "What will come of this friendship?",
    categoryId: "family-loved-ones",
    chapterId: "the-consequence-of-friendship-between-two-people",
    resultKind: null,
    methods: [{ id: "friendship-consequence-method-1", label: "Method 1", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "the-consequence-of-friendship-between-two-people" }],
  },
  "dreams-and-their-interpretations": {
    id: "dreams-and-their-interpretations",
    title: "What does this dream mean?",
    categoryId: "dreams",
    chapterId: "dreams-and-their-interpretations",
    resultKind: "descriptive",
    methods: [{ id: "dreams-interpretation-method-1", label: "Method 1", status: "verified", sourceBook: "kanzul-mikban", sourceChapterId: "dreams-and-their-interpretations" }],
  },
};

export const QUESTION_META_LIST: PublicQuestionMeta[] = Object.values(QUESTION_REGISTRY_META);

